// This file is auto-generated by @hey-api/openapi-ts

export const internal_handler_AvailableWindowResponseSchema = {
    properties: {
        adjacentSlotIds: {
            items: {
                type: 'integer'
            },
            type: 'array'
        },
        startSlot: {
            $ref: '#/definitions/internal_handler.SlotResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_AvailableWindowsListWrapSchema = {
    properties: {
        windows: {
            items: {
                $ref: '#/definitions/internal_handler.AvailableWindowResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_BookingResponseSchema = {
    properties: {
        clientName: {
            example: 'Иван Петров',
            type: 'string'
        },
        clientPhone: {
            example: '+79001234567',
            type: 'string'
        },
        clientType: {
            example: 'VK',
            type: 'string'
        },
        clientVkId: {
            example: 123456789,
            type: 'integer'
        },
        createdAt: {
            type: 'string'
        },
        customDurationMinutes: {
            example: 90,
            type: 'integer'
        },
        date: {
            example: '2026-04-15',
            type: 'string'
        },
        endTime: {
            example: '11:00',
            type: 'string'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        masterId: {
            example: 3,
            type: 'integer'
        },
        orgId: {
            example: 1,
            type: 'integer'
        },
        proposedDate: {
            example: '2026-04-16',
            type: 'string'
        },
        proposedEndTime: {
            example: '12:00',
            type: 'string'
        },
        proposedSlotId: {
            example: 55,
            type: 'integer'
        },
        proposedStartTime: {
            example: '11:00',
            type: 'string'
        },
        serviceId: {
            example: 7,
            type: 'integer'
        },
        slotId: {
            example: 42,
            type: 'integer'
        },
        startTime: {
            example: '10:00',
            type: 'string'
        },
        status: {
            example: 'CONFIRMED',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_BookingWrapSchema = {
    properties: {
        booking: {
            $ref: '#/definitions/internal_handler.BookingResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_BookingsListWrapSchema = {
    properties: {
        bookings: {
            items: {
                $ref: '#/definitions/internal_handler.BookingResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_ConfirmWaitlistSlotResponseSchema = {
    properties: {
        booking: {
            $ref: '#/definitions/internal_handler.BookingResponse'
        },
        entry: {
            $ref: '#/definitions/internal_handler.WaitlistEntryResponse'
        },
        slot: {
            $ref: '#/definitions/internal_handler.SlotResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_CreateBookingResponseSchema = {
    properties: {
        booking: {
            $ref: '#/definitions/internal_handler.BookingResponse'
        },
        slot: {
            $ref: '#/definitions/internal_handler.SlotShortResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_ErrorResponseSchema = {
    properties: {
        error: {
            example: 'invalid request',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_MasterProfileResponseSchema = {
    properties: {
        masterId: {
            example: 3,
            type: 'integer'
        },
        orgId: {
            example: 1,
            type: 'integer'
        },
        salonIds: {
            items: {
                type: 'integer'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_MasterResponseSchema = {
    properties: {
        createdAt: {
            type: 'string'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        isActive: {
            example: true,
            type: 'boolean'
        },
        name: {
            example: 'Анна Иванова',
            type: 'string'
        },
        orgId: {
            example: 1,
            type: 'integer'
        },
        salonIds: {
            items: {
                type: 'integer'
            },
            type: 'array'
        },
        vkId: {
            example: 123456789,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_MasterWrapSchema = {
    properties: {
        master: {
            $ref: '#/definitions/internal_handler.MasterResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_MastersListWrapSchema = {
    properties: {
        masters: {
            items: {
                $ref: '#/definitions/internal_handler.MasterResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_MeContextResponseSchema = {
    properties: {
        masterProfiles: {
            items: {
                $ref: '#/definitions/internal_handler.MasterProfileResponse'
            },
            type: 'array'
        },
        orgRoles: {
            items: {
                $ref: '#/definitions/internal_handler.OrgRoleEntryResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrgMemberResponseSchema = {
    properties: {
        orgId: {
            example: 1,
            type: 'integer'
        },
        roleId: {
            example: 2,
            type: 'integer'
        },
        roleName: {
            example: 'Администратор',
            type: 'string'
        },
        salonId: {
            example: 5,
            type: 'integer'
        },
        vkId: {
            example: 123456789,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrgMemberWrapSchema = {
    properties: {
        member: {
            $ref: '#/definitions/internal_handler.OrgMemberResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrgMembersListWrapSchema = {
    properties: {
        members: {
            items: {
                $ref: '#/definitions/internal_handler.OrgMemberResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrgRoleEntryResponseSchema = {
    properties: {
        orgId: {
            example: 1,
            type: 'integer'
        },
        permissions: {
            $ref: '#/definitions/internal_handler.OrgRolePermissionsResponse'
        },
        roleId: {
            example: 2,
            type: 'integer'
        },
        roleName: {
            example: 'Администратор',
            type: 'string'
        },
        salonId: {
            example: 5,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrgRolePermissionsResponseSchema = {
    properties: {
        all: {
            type: 'boolean'
        },
        bookClientsOthers: {
            type: 'boolean'
        },
        bookClientsSelf: {
            type: 'boolean'
        },
        changeBookingDurationOthers: {
            type: 'boolean'
        },
        changeBookingDurationSelf: {
            type: 'boolean'
        },
        editScheduleOthers: {
            type: 'boolean'
        },
        editScheduleSelf: {
            type: 'boolean'
        },
        manageBookingPeriodOthers: {
            type: 'boolean'
        },
        manageBookingPeriodSelf: {
            type: 'boolean'
        },
        manageExtraFieldOthers: {
            type: 'boolean'
        },
        manageExtraFieldSelf: {
            type: 'boolean'
        },
        manageOrgInfo: {
            type: 'boolean'
        },
        manageReminderOthers: {
            type: 'boolean'
        },
        manageReminderSelf: {
            type: 'boolean'
        },
        manageRoles: {
            type: 'boolean'
        },
        manageServiceMapOthers: {
            type: 'boolean'
        },
        manageServiceMapSelf: {
            type: 'boolean'
        },
        manageServicesOthers: {
            type: 'boolean'
        },
        manageServicesSelf: {
            type: 'boolean'
        },
        manageWorkIntervalsOthers: {
            type: 'boolean'
        },
        manageWorkIntervalsSelf: {
            type: 'boolean'
        },
        overrideWorkTimeOthers: {
            type: 'boolean'
        },
        overrideWorkTimeSelf: {
            type: 'boolean'
        },
        proposeRescheduleOthers: {
            type: 'boolean'
        },
        proposeRescheduleSelf: {
            type: 'boolean'
        },
        receiveNotificationsOthers: {
            type: 'boolean'
        },
        receiveNotificationsSelf: {
            type: 'boolean'
        },
        viewBookingsOthers: {
            type: 'boolean'
        },
        viewBookingsSelf: {
            type: 'boolean'
        },
        viewPastBookingsOthers: {
            type: 'boolean'
        },
        viewPastBookingsSelf: {
            type: 'boolean'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrgRoleResponseSchema = {
    properties: {
        id: {
            example: 1,
            type: 'integer'
        },
        isSystem: {
            example: false,
            type: 'boolean'
        },
        name: {
            example: 'Администратор',
            type: 'string'
        },
        orgId: {
            example: 1,
            type: 'integer'
        },
        permissions: {
            $ref: '#/definitions/internal_handler.OrgRolePermissionsResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrgRoleWrapSchema = {
    properties: {
        role: {
            $ref: '#/definitions/internal_handler.OrgRoleResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrgRolesListWrapSchema = {
    properties: {
        roles: {
            items: {
                $ref: '#/definitions/internal_handler.OrgRoleResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrganizationResponseSchema = {
    properties: {
        createdAt: {
            type: 'string'
        },
        createdByVkId: {
            example: 123456789,
            type: 'integer'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        maxLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        },
        name: {
            example: 'Салон красоты Анна',
            type: 'string'
        },
        phones: {
            example: [
                '["+79001234567"]'
            ],
            items: {
                type: 'string'
            },
            type: 'array'
        },
        rescheduleReminderHours: {
            example: 24,
            type: 'integer'
        },
        tgLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        },
        vkLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        },
        waitlistConfirmationHours: {
            example: 2,
            type: 'integer'
        },
        websiteLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_OrganizationWrapSchema = {
    properties: {
        organization: {
            $ref: '#/definitions/internal_handler.OrganizationResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SalonResponseSchema = {
    properties: {
        createdAt: {
            type: 'string'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        isActive: {
            example: true,
            type: 'boolean'
        },
        name: {
            example: 'Салон на Тверской',
            type: 'string'
        },
        orgId: {
            example: 1,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SalonWrapSchema = {
    properties: {
        salon: {
            $ref: '#/definitions/internal_handler.SalonResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SalonsListWrapSchema = {
    properties: {
        salons: {
            items: {
                $ref: '#/definitions/internal_handler.SalonResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_ScheduleExceptionResponseSchema = {
    properties: {
        date: {
            example: '2026-04-15',
            type: 'string'
        },
        endTime: {
            example: '15:00',
            type: 'string'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        isDayOff: {
            example: true,
            type: 'boolean'
        },
        masterId: {
            example: 3,
            type: 'integer'
        },
        salonId: {
            example: 2,
            type: 'integer'
        },
        startTime: {
            example: '11:00',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_ScheduleExceptionWrapSchema = {
    properties: {
        exception: {
            $ref: '#/definitions/internal_handler.ScheduleExceptionResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_ScheduleExceptionsListWrapSchema = {
    properties: {
        exceptions: {
            items: {
                $ref: '#/definitions/internal_handler.ScheduleExceptionResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SearchResultItemResponseSchema = {
    properties: {
        org: {
            $ref: '#/definitions/internal_handler.SearchServiceOrgResponse'
        },
        service: {
            $ref: '#/definitions/internal_handler.SearchServiceDetailResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SearchServiceDetailResponseSchema = {
    properties: {
        durationMinutes: {
            example: 60,
            type: 'integer'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        name: {
            example: 'Стрижка',
            type: 'string'
        },
        orgId: {
            example: 1,
            type: 'integer'
        },
        price: {
            example: 1500,
            type: 'number'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SearchServiceOrgResponseSchema = {
    properties: {
        createdByVkId: {
            example: 123456789,
            type: 'integer'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        name: {
            example: 'Салон красоты Анна',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SearchServicesResponseSchema = {
    properties: {
        results: {
            items: {
                $ref: '#/definitions/internal_handler.SearchResultItemResponse'
            },
            type: 'array'
        },
        totalCount: {
            example: 42,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_ServiceResponseSchema = {
    properties: {
        description: {
            example: 'Классическая мужская стрижка',
            type: 'string'
        },
        durationMinutes: {
            example: 60,
            type: 'integer'
        },
        extraFieldLabel: {
            example: 'VIN номер',
            type: 'string'
        },
        extraFieldRequired: {
            example: true,
            type: 'boolean'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        isActive: {
            example: true,
            type: 'boolean'
        },
        name: {
            example: 'Стрижка',
            type: 'string'
        },
        orgId: {
            example: 1,
            type: 'integer'
        },
        price: {
            example: 1500,
            type: 'number'
        },
        reminderHours: {
            example: 24,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_ServiceWrapSchema = {
    properties: {
        service: {
            $ref: '#/definitions/internal_handler.ServiceResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_ServicesListWrapSchema = {
    properties: {
        services: {
            items: {
                $ref: '#/definitions/internal_handler.ServiceResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SetWorkScheduleResponseWrapSchema = {
    properties: {
        scheduleCount: {
            example: 5,
            type: 'integer'
        },
        schedules: {
            items: {
                $ref: '#/definitions/internal_handler.WorkScheduleResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SlotResponseSchema = {
    properties: {
        date: {
            example: '2026-04-15',
            type: 'string'
        },
        endTime: {
            example: '11:00',
            type: 'string'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        masterId: {
            example: 3,
            type: 'integer'
        },
        masterName: {
            example: 'Анна Иванова',
            type: 'string'
        },
        orgId: {
            example: 1,
            type: 'integer'
        },
        slotDurationMinutes: {
            example: 60,
            type: 'integer'
        },
        startTime: {
            example: '10:00',
            type: 'string'
        },
        status: {
            example: 'AVAILABLE',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SlotShortResponseSchema = {
    properties: {
        id: {
            example: 42,
            type: 'integer'
        },
        status: {
            example: 'BOOKED',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_SlotsListWrapSchema = {
    properties: {
        slots: {
            items: {
                $ref: '#/definitions/internal_handler.SlotResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_WaitlistEntriesListWrapSchema = {
    properties: {
        entries: {
            items: {
                $ref: '#/definitions/internal_handler.WaitlistEntryResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_WaitlistEntryResponseSchema = {
    properties: {
        confirmationDeadline: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        orgId: {
            example: 1,
            type: 'integer'
        },
        preferredDateFrom: {
            example: '2026-04-01',
            type: 'string'
        },
        preferredDateTo: {
            example: '2026-04-30',
            type: 'string'
        },
        preferredTimeFrom: {
            example: '09:00',
            type: 'string'
        },
        preferredTimeTo: {
            example: '18:00',
            type: 'string'
        },
        reservedSlotDate: {
            example: '2026-04-15',
            type: 'string'
        },
        reservedSlotEndTime: {
            example: '11:00',
            type: 'string'
        },
        reservedSlotId: {
            example: 42,
            type: 'integer'
        },
        reservedSlotStartTime: {
            example: '10:00',
            type: 'string'
        },
        serviceId: {
            example: 7,
            type: 'integer'
        },
        status: {
            example: 'PENDING',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_WaitlistEntryWrapSchema = {
    properties: {
        entry: {
            $ref: '#/definitions/internal_handler.WaitlistEntryResponse'
        }
    },
    type: 'object'
} as const;

export const internal_handler_WorkScheduleResponseSchema = {
    properties: {
        dayOfWeek: {
            example: 1,
            type: 'integer'
        },
        endTime: {
            example: '18:00',
            type: 'string'
        },
        id: {
            example: 1,
            type: 'integer'
        },
        masterId: {
            example: 3,
            type: 'integer'
        },
        salonId: {
            example: 2,
            type: 'integer'
        },
        startTime: {
            example: '09:00',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_WorkSchedulesListWrapSchema = {
    properties: {
        schedules: {
            items: {
                $ref: '#/definitions/internal_handler.WorkScheduleResponse'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_addOrgMemberRequestSchema = {
    properties: {
        roleId: {
            example: 2,
            type: 'integer'
        },
        salonId: {
            example: 5,
            type: 'integer'
        },
        vkId: {
            example: 123456789,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_addSalonPhoneRequestSchema = {
    properties: {
        phone: {
            example: '+79001234567',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_createManualBookingRequestSchema = {
    properties: {
        additionalSlotIds: {
            items: {
                type: 'integer'
            },
            type: 'array'
        },
        clientName: {
            example: 'Иван Петров',
            type: 'string'
        },
        clientPhone: {
            example: '+79001234567',
            type: 'string'
        },
        clientType: {
            description: '"VK" or "MANUAL"',
            example: 'MANUAL',
            type: 'string'
        },
        clientVkId: {
            example: 123456789,
            type: 'integer'
        },
        customDurationMinutes: {
            example: 60,
            type: 'integer'
        },
        date: {
            example: '2026-04-15',
            type: 'string'
        },
        endTime: {
            example: '11:00',
            type: 'string'
        },
        extraFieldValue: {
            example: 'X9F123456789012345',
            type: 'string'
        },
        masterId: {
            description: '0 = no master',
            example: 3,
            type: 'integer'
        },
        serviceId: {
            example: 7,
            type: 'integer'
        },
        slotId: {
            example: 42,
            type: 'integer'
        },
        startTime: {
            example: '10:00',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_createMasterRequestSchema = {
    properties: {
        name: {
            example: 'Анна Иванова',
            type: 'string'
        },
        vkId: {
            example: 123456789,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_createOrgRoleRequestSchema = {
    properties: {
        name: {
            example: 'Администратор',
            type: 'string'
        },
        permissions: {
            $ref: '#/definitions/internal_handler.orgRolePermissionsRequest'
        }
    },
    type: 'object'
} as const;

export const internal_handler_createOrganizationRequestSchema = {
    properties: {
        maxLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        },
        name: {
            example: 'Салон красоты Анна',
            type: 'string'
        },
        phones: {
            example: [
                '["+79001234567"]'
            ],
            items: {
                type: 'string'
            },
            type: 'array'
        },
        tgLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        },
        vkLinks: {
            example: [
                '["https://vk.com/salonanna"]'
            ],
            items: {
                type: 'string'
            },
            type: 'array'
        },
        websiteLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_createPublicBookingRequestSchema = {
    properties: {
        adjacentSlotIds: {
            items: {
                type: 'integer'
            },
            type: 'array'
        },
        date: {
            example: '2026-04-15',
            type: 'string'
        },
        endTime: {
            example: '11:00',
            type: 'string'
        },
        extraFieldValue: {
            example: 'X9F123456789012345',
            type: 'string'
        },
        masterId: {
            example: 3,
            type: 'integer'
        },
        serviceId: {
            example: 7,
            type: 'integer'
        },
        slotId: {
            example: 42,
            type: 'integer'
        },
        startTime: {
            example: '10:00',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_createSalonRequestSchema = {
    properties: {
        name: {
            example: 'Салон на Тверской',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_createServiceRequestSchema = {
    properties: {
        description: {
            example: 'Классическая мужская стрижка',
            type: 'string'
        },
        durationMinutes: {
            example: 60,
            type: 'integer'
        },
        extraFieldLabel: {
            example: 'VIN номер',
            type: 'string'
        },
        extraFieldRequired: {
            example: true,
            type: 'boolean'
        },
        name: {
            example: 'Стрижка',
            type: 'string'
        },
        price: {
            example: 1500,
            type: 'integer'
        },
        reminderHours: {
            example: 2,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_deleteExceptionRequestSchema = {
    properties: {
        slotDurationMinutes: {
            example: 30,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_generateSlotIntervalSchema = {
    properties: {
        endDate: {
            example: '2026-04-30',
            type: 'string'
        },
        endTime: {
            example: '18:00',
            type: 'string'
        },
        masterId: {
            example: 3,
            type: 'integer'
        },
        slotDurationMinutes: {
            example: 60,
            type: 'integer'
        },
        startDate: {
            example: '2026-04-01',
            type: 'string'
        },
        startTime: {
            example: '09:00',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_joinWaitlistRequestSchema = {
    properties: {
        preferredDateFrom: {
            type: 'string'
        },
        preferredDateTo: {
            type: 'string'
        },
        preferredTimeFrom: {
            type: 'string'
        },
        preferredTimeTo: {
            type: 'string'
        },
        serviceId: {
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_orgRolePermissionsRequestSchema = {
    properties: {
        all: {
            type: 'boolean'
        },
        bookClientsOthers: {
            type: 'boolean'
        },
        bookClientsSelf: {
            type: 'boolean'
        },
        changeBookingDurationOthers: {
            type: 'boolean'
        },
        changeBookingDurationSelf: {
            type: 'boolean'
        },
        editScheduleOthers: {
            type: 'boolean'
        },
        editScheduleSelf: {
            type: 'boolean'
        },
        manageBookingPeriodOthers: {
            type: 'boolean'
        },
        manageBookingPeriodSelf: {
            type: 'boolean'
        },
        manageExtraFieldOthers: {
            type: 'boolean'
        },
        manageExtraFieldSelf: {
            type: 'boolean'
        },
        manageOrgInfo: {
            type: 'boolean'
        },
        manageReminderOthers: {
            type: 'boolean'
        },
        manageReminderSelf: {
            type: 'boolean'
        },
        manageRoles: {
            type: 'boolean'
        },
        manageServiceMapOthers: {
            type: 'boolean'
        },
        manageServiceMapSelf: {
            type: 'boolean'
        },
        manageServicesOthers: {
            type: 'boolean'
        },
        manageServicesSelf: {
            type: 'boolean'
        },
        manageWorkIntervalsOthers: {
            type: 'boolean'
        },
        manageWorkIntervalsSelf: {
            type: 'boolean'
        },
        overrideWorkTimeOthers: {
            type: 'boolean'
        },
        overrideWorkTimeSelf: {
            type: 'boolean'
        },
        proposeRescheduleOthers: {
            type: 'boolean'
        },
        proposeRescheduleSelf: {
            type: 'boolean'
        },
        receiveNotificationsOthers: {
            type: 'boolean'
        },
        receiveNotificationsSelf: {
            type: 'boolean'
        },
        viewBookingsOthers: {
            type: 'boolean'
        },
        viewBookingsSelf: {
            type: 'boolean'
        },
        viewPastBookingsOthers: {
            type: 'boolean'
        },
        viewPastBookingsSelf: {
            type: 'boolean'
        }
    },
    type: 'object'
} as const;

export const internal_handler_proposeRescheduleRequestSchema = {
    properties: {
        newSlotId: {
            example: 55,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_respondToRescheduleRequestSchema = {
    properties: {
        accept: {
            example: true,
            type: 'boolean'
        }
    },
    type: 'object'
} as const;

export const internal_handler_scheduleExceptionRequestSchema = {
    properties: {
        endTime: {
            example: '15:00',
            type: 'string'
        },
        isDayOff: {
            example: false,
            type: 'boolean'
        },
        slotDurationMinutes: {
            example: 30,
            type: 'integer'
        },
        startTime: {
            example: '11:00',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_setWorkScheduleRequestSchema = {
    properties: {
        schedules: {
            items: {
                $ref: '#/definitions/internal_handler.workScheduleRow'
            },
            type: 'array'
        },
        slotDurationMinutes: {
            example: 30,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_updateBookingDurationRequestSchema = {
    properties: {
        additionalSlotIds: {
            items: {
                type: 'integer'
            },
            type: 'array'
        },
        customDurationMinutes: {
            example: 90,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_updateBookingStatusRequestSchema = {
    properties: {
        slotId: {
            example: 42,
            type: 'integer'
        },
        status: {
            example: 'CONFIRMED',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_updateMasterRequestSchema = {
    properties: {
        feedbackLink: {
            example: 'https://example.com/reviews',
            type: 'string'
        },
        isActive: {
            example: true,
            type: 'boolean'
        },
        name: {
            example: 'Анна Иванова',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_updateOrgRoleRequestSchema = {
    properties: {
        name: {
            example: 'Администратор',
            type: 'string'
        },
        permissions: {
            $ref: '#/definitions/internal_handler.orgRolePermissionsRequest'
        }
    },
    type: 'object'
} as const;

export const internal_handler_updateOrganizationRequestSchema = {
    properties: {
        maxLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        },
        name: {
            example: 'Салон красоты Анна',
            type: 'string'
        },
        phones: {
            example: [
                '["+79001234567"]'
            ],
            items: {
                type: 'string'
            },
            type: 'array'
        },
        rescheduleReminderHours: {
            example: 24,
            type: 'integer'
        },
        tgLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        },
        vkLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        },
        waitlistConfirmationHours: {
            example: 2,
            type: 'integer'
        },
        websiteLinks: {
            items: {
                type: 'string'
            },
            type: 'array'
        }
    },
    type: 'object'
} as const;

export const internal_handler_updateSalonRequestSchema = {
    properties: {
        isActive: {
            example: true,
            type: 'boolean'
        },
        name: {
            example: 'Салон на Тверской',
            type: 'string'
        }
    },
    type: 'object'
} as const;

export const internal_handler_updateServiceRequestSchema = {
    properties: {
        description: {
            example: 'Классическая мужская стрижка',
            type: 'string'
        },
        durationMinutes: {
            example: 60,
            type: 'integer'
        },
        extraFieldLabel: {
            example: 'VIN номер',
            type: 'string'
        },
        extraFieldRequired: {
            example: true,
            type: 'boolean'
        },
        isActive: {
            example: true,
            type: 'boolean'
        },
        name: {
            example: 'Стрижка',
            type: 'string'
        },
        price: {
            example: 1500,
            type: 'integer'
        },
        reminderHours: {
            example: 2,
            type: 'integer'
        }
    },
    type: 'object'
} as const;

export const internal_handler_workScheduleRowSchema = {
    properties: {
        dayOfWeek: {
            example: 1,
            type: 'integer'
        },
        endTime: {
            example: '18:00',
            type: 'string'
        },
        startTime: {
            example: '09:00',
            type: 'string'
        }
    },
    type: 'object'
} as const;
