// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'localhost:8080/api/v1' | (string & {});
};

export type InternalHandlerAvailableWindowResponse = {
    adjacentSlotIds?: Array<number>;
    startSlot?: InternalHandlerSlotResponse;
};

export type InternalHandlerAvailableWindowsListWrap = {
    windows?: Array<InternalHandlerAvailableWindowResponse>;
};

export type InternalHandlerBookingResponse = {
    clientName?: string;
    clientPhone?: string;
    clientType?: string;
    clientVkId?: number;
    createdAt?: string;
    customDurationMinutes?: number;
    date?: string;
    endTime?: string;
    id?: number;
    masterId?: number;
    orgId?: number;
    proposedDate?: string;
    proposedEndTime?: string;
    proposedSlotId?: number;
    proposedStartTime?: string;
    serviceId?: number;
    slotId?: number;
    startTime?: string;
    status?: string;
};

export type InternalHandlerBookingWrap = {
    booking?: InternalHandlerBookingResponse;
};

export type InternalHandlerBookingsListWrap = {
    bookings?: Array<InternalHandlerBookingResponse>;
};

export type InternalHandlerConfirmWaitlistSlotResponse = {
    booking?: InternalHandlerBookingResponse;
    entry?: InternalHandlerWaitlistEntryResponse;
    slot?: InternalHandlerSlotResponse;
};

export type InternalHandlerCreateBookingResponse = {
    booking?: InternalHandlerBookingResponse;
    slot?: InternalHandlerSlotShortResponse;
};

export type InternalHandlerErrorResponse = {
    error?: string;
};

export type InternalHandlerMasterProfileResponse = {
    masterId?: number;
    orgId?: number;
    salonIds?: Array<number>;
};

export type InternalHandlerMasterResponse = {
    createdAt?: string;
    id?: number;
    isActive?: boolean;
    name?: string;
    orgId?: number;
    salonIds?: Array<number>;
    vkId?: number;
};

export type InternalHandlerMasterWrap = {
    master?: InternalHandlerMasterResponse;
};

export type InternalHandlerMastersListWrap = {
    masters?: Array<InternalHandlerMasterResponse>;
};

export type InternalHandlerMeContextResponse = {
    masterProfiles?: Array<InternalHandlerMasterProfileResponse>;
    orgRoles?: Array<InternalHandlerOrgRoleEntryResponse>;
};

export type InternalHandlerOrgMemberResponse = {
    orgId?: number;
    roleId?: number;
    roleName?: string;
    salonId?: number;
    vkId?: number;
};

export type InternalHandlerOrgMemberWrap = {
    member?: InternalHandlerOrgMemberResponse;
};

export type InternalHandlerOrgMembersListWrap = {
    members?: Array<InternalHandlerOrgMemberResponse>;
};

export type InternalHandlerOrgRoleEntryResponse = {
    orgId?: number;
    permissions?: InternalHandlerOrgRolePermissionsResponse;
    roleId?: number;
    roleName?: string;
    salonId?: number;
};

export type InternalHandlerOrgRolePermissionsResponse = {
    all?: boolean;
    bookClientsOthers?: boolean;
    bookClientsSelf?: boolean;
    changeBookingDurationOthers?: boolean;
    changeBookingDurationSelf?: boolean;
    editScheduleOthers?: boolean;
    editScheduleSelf?: boolean;
    manageBookingPeriodOthers?: boolean;
    manageBookingPeriodSelf?: boolean;
    manageExtraFieldOthers?: boolean;
    manageExtraFieldSelf?: boolean;
    manageOrgInfo?: boolean;
    manageReminderOthers?: boolean;
    manageReminderSelf?: boolean;
    manageRoles?: boolean;
    manageServiceMapOthers?: boolean;
    manageServiceMapSelf?: boolean;
    manageServicesOthers?: boolean;
    manageServicesSelf?: boolean;
    manageWorkIntervalsOthers?: boolean;
    manageWorkIntervalsSelf?: boolean;
    overrideWorkTimeOthers?: boolean;
    overrideWorkTimeSelf?: boolean;
    proposeRescheduleOthers?: boolean;
    proposeRescheduleSelf?: boolean;
    receiveNotificationsOthers?: boolean;
    receiveNotificationsSelf?: boolean;
    viewBookingsOthers?: boolean;
    viewBookingsSelf?: boolean;
    viewPastBookingsOthers?: boolean;
    viewPastBookingsSelf?: boolean;
};

export type InternalHandlerOrgRoleResponse = {
    id?: number;
    isSystem?: boolean;
    name?: string;
    orgId?: number;
    permissions?: InternalHandlerOrgRolePermissionsResponse;
};

export type InternalHandlerOrgRoleWrap = {
    role?: InternalHandlerOrgRoleResponse;
};

export type InternalHandlerOrgRolesListWrap = {
    roles?: Array<InternalHandlerOrgRoleResponse>;
};

export type InternalHandlerOrganizationResponse = {
    createdAt?: string;
    createdByVkId?: number;
    id?: number;
    maxLinks?: Array<string>;
    name?: string;
    phones?: Array<string>;
    rescheduleReminderHours?: number;
    tgLinks?: Array<string>;
    vkLinks?: Array<string>;
    waitlistConfirmationHours?: number;
    websiteLinks?: Array<string>;
};

export type InternalHandlerOrganizationWrap = {
    organization?: InternalHandlerOrganizationResponse;
};

export type InternalHandlerSalonResponse = {
    createdAt?: string;
    id?: number;
    isActive?: boolean;
    name?: string;
    orgId?: number;
};

export type InternalHandlerSalonWrap = {
    salon?: InternalHandlerSalonResponse;
};

export type InternalHandlerSalonsListWrap = {
    salons?: Array<InternalHandlerSalonResponse>;
};

export type InternalHandlerScheduleExceptionResponse = {
    date?: string;
    endTime?: string;
    id?: number;
    isDayOff?: boolean;
    masterId?: number;
    salonId?: number;
    startTime?: string;
};

export type InternalHandlerScheduleExceptionWrap = {
    exception?: InternalHandlerScheduleExceptionResponse;
};

export type InternalHandlerScheduleExceptionsListWrap = {
    exceptions?: Array<InternalHandlerScheduleExceptionResponse>;
};

export type InternalHandlerSearchResultItemResponse = {
    org?: InternalHandlerSearchServiceOrgResponse;
    service?: InternalHandlerSearchServiceDetailResponse;
};

export type InternalHandlerSearchServiceDetailResponse = {
    durationMinutes?: number;
    id?: number;
    name?: string;
    orgId?: number;
    price?: number;
};

export type InternalHandlerSearchServiceOrgResponse = {
    createdByVkId?: number;
    id?: number;
    name?: string;
};

export type InternalHandlerSearchServicesResponse = {
    results?: Array<InternalHandlerSearchResultItemResponse>;
    totalCount?: number;
};

export type InternalHandlerServiceResponse = {
    description?: string;
    durationMinutes?: number;
    extraFieldLabel?: string;
    extraFieldRequired?: boolean;
    id?: number;
    isActive?: boolean;
    name?: string;
    orgId?: number;
    price?: number;
    reminderHours?: number;
};

export type InternalHandlerServiceWrap = {
    service?: InternalHandlerServiceResponse;
};

export type InternalHandlerServicesListWrap = {
    services?: Array<InternalHandlerServiceResponse>;
};

export type InternalHandlerSetWorkScheduleResponseWrap = {
    scheduleCount?: number;
    schedules?: Array<InternalHandlerWorkScheduleResponse>;
};

export type InternalHandlerSlotResponse = {
    date?: string;
    endTime?: string;
    id?: number;
    masterId?: number;
    masterName?: string;
    orgId?: number;
    slotDurationMinutes?: number;
    startTime?: string;
    status?: string;
};

export type InternalHandlerSlotShortResponse = {
    id?: number;
    status?: string;
};

export type InternalHandlerSlotsListWrap = {
    slots?: Array<InternalHandlerSlotResponse>;
};

export type InternalHandlerWaitlistEntriesListWrap = {
    entries?: Array<InternalHandlerWaitlistEntryResponse>;
};

export type InternalHandlerWaitlistEntryResponse = {
    confirmationDeadline?: string;
    createdAt?: string;
    id?: number;
    orgId?: number;
    preferredDateFrom?: string;
    preferredDateTo?: string;
    preferredTimeFrom?: string;
    preferredTimeTo?: string;
    reservedSlotDate?: string;
    reservedSlotEndTime?: string;
    reservedSlotId?: number;
    reservedSlotStartTime?: string;
    serviceId?: number;
    status?: string;
};

export type InternalHandlerWaitlistEntryWrap = {
    entry?: InternalHandlerWaitlistEntryResponse;
};

export type InternalHandlerWorkScheduleResponse = {
    dayOfWeek?: number;
    endTime?: string;
    id?: number;
    masterId?: number;
    salonId?: number;
    startTime?: string;
};

export type InternalHandlerWorkSchedulesListWrap = {
    schedules?: Array<InternalHandlerWorkScheduleResponse>;
};

export type InternalHandlerAddOrgMemberRequest = {
    roleId?: number;
    salonId?: number;
    vkId?: number;
};

export type InternalHandlerAddSalonPhoneRequest = {
    phone?: string;
};

export type InternalHandlerCreateManualBookingRequest = {
    additionalSlotIds?: Array<number>;
    clientName?: string;
    clientPhone?: string;
    /**
     * "VK" or "MANUAL"
     */
    clientType?: string;
    clientVkId?: number;
    customDurationMinutes?: number;
    date?: string;
    endTime?: string;
    extraFieldValue?: string;
    /**
     * 0 = no master
     */
    masterId?: number;
    serviceId?: number;
    slotId?: number;
    startTime?: string;
};

export type InternalHandlerCreateMasterRequest = {
    name?: string;
    vkId?: number;
};

export type InternalHandlerCreateOrgRoleRequest = {
    name?: string;
    permissions?: InternalHandlerOrgRolePermissionsRequest;
};

export type InternalHandlerCreateOrganizationRequest = {
    maxLinks?: Array<string>;
    name?: string;
    phones?: Array<string>;
    tgLinks?: Array<string>;
    vkLinks?: Array<string>;
    websiteLinks?: Array<string>;
};

export type InternalHandlerCreatePublicBookingRequest = {
    adjacentSlotIds?: Array<number>;
    date?: string;
    endTime?: string;
    extraFieldValue?: string;
    masterId?: number;
    serviceId?: number;
    slotId?: number;
    startTime?: string;
};

export type InternalHandlerCreateSalonRequest = {
    name?: string;
};

export type InternalHandlerCreateServiceRequest = {
    description?: string;
    durationMinutes?: number;
    extraFieldLabel?: string;
    extraFieldRequired?: boolean;
    name?: string;
    price?: number;
    reminderHours?: number;
};

export type InternalHandlerDeleteExceptionRequest = {
    slotDurationMinutes?: number;
};

export type InternalHandlerGenerateSlotInterval = {
    endDate?: string;
    endTime?: string;
    masterId?: number;
    slotDurationMinutes?: number;
    startDate?: string;
    startTime?: string;
};

export type InternalHandlerJoinWaitlistRequest = {
    preferredDateFrom?: string;
    preferredDateTo?: string;
    preferredTimeFrom?: string;
    preferredTimeTo?: string;
    serviceId?: number;
};

export type InternalHandlerOrgRolePermissionsRequest = {
    all?: boolean;
    bookClientsOthers?: boolean;
    bookClientsSelf?: boolean;
    changeBookingDurationOthers?: boolean;
    changeBookingDurationSelf?: boolean;
    editScheduleOthers?: boolean;
    editScheduleSelf?: boolean;
    manageBookingPeriodOthers?: boolean;
    manageBookingPeriodSelf?: boolean;
    manageExtraFieldOthers?: boolean;
    manageExtraFieldSelf?: boolean;
    manageOrgInfo?: boolean;
    manageReminderOthers?: boolean;
    manageReminderSelf?: boolean;
    manageRoles?: boolean;
    manageServiceMapOthers?: boolean;
    manageServiceMapSelf?: boolean;
    manageServicesOthers?: boolean;
    manageServicesSelf?: boolean;
    manageWorkIntervalsOthers?: boolean;
    manageWorkIntervalsSelf?: boolean;
    overrideWorkTimeOthers?: boolean;
    overrideWorkTimeSelf?: boolean;
    proposeRescheduleOthers?: boolean;
    proposeRescheduleSelf?: boolean;
    receiveNotificationsOthers?: boolean;
    receiveNotificationsSelf?: boolean;
    viewBookingsOthers?: boolean;
    viewBookingsSelf?: boolean;
    viewPastBookingsOthers?: boolean;
    viewPastBookingsSelf?: boolean;
};

export type InternalHandlerProposeRescheduleRequest = {
    newSlotId?: number;
};

export type InternalHandlerRespondToRescheduleRequest = {
    accept?: boolean;
};

export type InternalHandlerScheduleExceptionRequest = {
    endTime?: string;
    isDayOff?: boolean;
    slotDurationMinutes?: number;
    startTime?: string;
};

export type InternalHandlerSetWorkScheduleRequest = {
    schedules?: Array<InternalHandlerWorkScheduleRow>;
    slotDurationMinutes?: number;
};

export type InternalHandlerUpdateBookingDurationRequest = {
    additionalSlotIds?: Array<number>;
    customDurationMinutes?: number;
};

export type InternalHandlerUpdateBookingStatusRequest = {
    slotId?: number;
    status?: string;
};

export type InternalHandlerUpdateMasterRequest = {
    feedbackLink?: string;
    isActive?: boolean;
    name?: string;
};

export type InternalHandlerUpdateOrgRoleRequest = {
    name?: string;
    permissions?: InternalHandlerOrgRolePermissionsRequest;
};

export type InternalHandlerUpdateOrganizationRequest = {
    maxLinks?: Array<string>;
    name?: string;
    phones?: Array<string>;
    rescheduleReminderHours?: number;
    tgLinks?: Array<string>;
    vkLinks?: Array<string>;
    waitlistConfirmationHours?: number;
    websiteLinks?: Array<string>;
};

export type InternalHandlerUpdateSalonRequest = {
    isActive?: boolean;
    name?: string;
};

export type InternalHandlerUpdateServiceRequest = {
    description?: string;
    durationMinutes?: number;
    extraFieldLabel?: string;
    extraFieldRequired?: boolean;
    isActive?: boolean;
    name?: string;
    price?: number;
    reminderHours?: number;
};

export type InternalHandlerWorkScheduleRow = {
    dayOfWeek?: number;
    endTime?: string;
    startTime?: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetMeContextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/context';
};

export type GetMeContextErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetMeContextError = GetMeContextErrors[keyof GetMeContextErrors];

export type GetMeContextResponses = {
    /**
     * OK
     */
    200: InternalHandlerMeContextResponse;
};

export type GetMeContextResponse = GetMeContextResponses[keyof GetMeContextResponses];

export type PostOrganizationsData = {
    /**
     * Данные организации
     */
    body: InternalHandlerCreateOrganizationRequest;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type PostOrganizationsErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsError = PostOrganizationsErrors[keyof PostOrganizationsErrors];

export type PostOrganizationsResponses = {
    /**
     * Created
     */
    201: InternalHandlerOrganizationWrap;
};

export type PostOrganizationsResponse = PostOrganizationsResponses[keyof PostOrganizationsResponses];

export type GetOrganizationsByOrgIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}';
};

export type GetOrganizationsByOrgIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdError = GetOrganizationsByOrgIdErrors[keyof GetOrganizationsByOrgIdErrors];

export type GetOrganizationsByOrgIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerOrganizationWrap;
};

export type GetOrganizationsByOrgIdResponse = GetOrganizationsByOrgIdResponses[keyof GetOrganizationsByOrgIdResponses];

export type PutOrganizationsByOrgIdData = {
    /**
     * Обновленные данные организации
     */
    body: InternalHandlerUpdateOrganizationRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}';
};

export type PutOrganizationsByOrgIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PutOrganizationsByOrgIdError = PutOrganizationsByOrgIdErrors[keyof PutOrganizationsByOrgIdErrors];

export type PutOrganizationsByOrgIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerOrganizationWrap;
};

export type PutOrganizationsByOrgIdResponse = PutOrganizationsByOrgIdResponses[keyof PutOrganizationsByOrgIdResponses];

export type GetOrganizationsByOrgIdBookingsData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: {
        /**
         * Дата (YYYY-MM-DD)
         */
        date?: string;
        /**
         * Статус (PENDING, CONFIRMED, REJECTED, CANCELLED)
         */
        status?: string;
    };
    url: '/organizations/{org_id}/bookings';
};

export type GetOrganizationsByOrgIdBookingsErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdBookingsError = GetOrganizationsByOrgIdBookingsErrors[keyof GetOrganizationsByOrgIdBookingsErrors];

export type GetOrganizationsByOrgIdBookingsResponses = {
    /**
     * OK
     */
    200: InternalHandlerBookingsListWrap;
};

export type GetOrganizationsByOrgIdBookingsResponse = GetOrganizationsByOrgIdBookingsResponses[keyof GetOrganizationsByOrgIdBookingsResponses];

export type PostOrganizationsByOrgIdBookingsData = {
    /**
     * Данные записи
     */
    body: InternalHandlerCreateManualBookingRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/bookings';
};

export type PostOrganizationsByOrgIdBookingsErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Conflict
     */
    409: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdBookingsError = PostOrganizationsByOrgIdBookingsErrors[keyof PostOrganizationsByOrgIdBookingsErrors];

export type PostOrganizationsByOrgIdBookingsResponses = {
    /**
     * Created
     */
    201: InternalHandlerCreateBookingResponse;
};

export type PostOrganizationsByOrgIdBookingsResponse = PostOrganizationsByOrgIdBookingsResponses[keyof PostOrganizationsByOrgIdBookingsResponses];

export type PatchOrganizationsByOrgIdBookingsByIdDurationData = {
    /**
     * Новая длительность
     */
    body: InternalHandlerUpdateBookingDurationRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID бронирования
         */
        id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/bookings/{id}/duration';
};

export type PatchOrganizationsByOrgIdBookingsByIdDurationErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Not Found
     */
    404: InternalHandlerErrorResponse;
    /**
     * Conflict
     */
    409: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PatchOrganizationsByOrgIdBookingsByIdDurationError = PatchOrganizationsByOrgIdBookingsByIdDurationErrors[keyof PatchOrganizationsByOrgIdBookingsByIdDurationErrors];

export type PatchOrganizationsByOrgIdBookingsByIdDurationResponses = {
    /**
     * OK
     */
    200: InternalHandlerBookingWrap;
};

export type PatchOrganizationsByOrgIdBookingsByIdDurationResponse = PatchOrganizationsByOrgIdBookingsByIdDurationResponses[keyof PatchOrganizationsByOrgIdBookingsByIdDurationResponses];

export type DeleteOrganizationsByOrgIdBookingsByIdRescheduleData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID бронирования
         */
        id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/bookings/{id}/reschedule';
};

export type DeleteOrganizationsByOrgIdBookingsByIdRescheduleErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Not Found
     */
    404: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeleteOrganizationsByOrgIdBookingsByIdRescheduleError = DeleteOrganizationsByOrgIdBookingsByIdRescheduleErrors[keyof DeleteOrganizationsByOrgIdBookingsByIdRescheduleErrors];

export type DeleteOrganizationsByOrgIdBookingsByIdRescheduleResponses = {
    /**
     * OK
     */
    200: InternalHandlerBookingWrap;
};

export type DeleteOrganizationsByOrgIdBookingsByIdRescheduleResponse = DeleteOrganizationsByOrgIdBookingsByIdRescheduleResponses[keyof DeleteOrganizationsByOrgIdBookingsByIdRescheduleResponses];

export type PostOrganizationsByOrgIdBookingsByIdRescheduleData = {
    /**
     * ID нового слота
     */
    body: InternalHandlerProposeRescheduleRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID бронирования
         */
        id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/bookings/{id}/reschedule';
};

export type PostOrganizationsByOrgIdBookingsByIdRescheduleErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Not Found
     */
    404: InternalHandlerErrorResponse;
    /**
     * Conflict
     */
    409: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdBookingsByIdRescheduleError = PostOrganizationsByOrgIdBookingsByIdRescheduleErrors[keyof PostOrganizationsByOrgIdBookingsByIdRescheduleErrors];

export type PostOrganizationsByOrgIdBookingsByIdRescheduleResponses = {
    /**
     * OK
     */
    200: InternalHandlerBookingWrap;
};

export type PostOrganizationsByOrgIdBookingsByIdRescheduleResponse = PostOrganizationsByOrgIdBookingsByIdRescheduleResponses[keyof PostOrganizationsByOrgIdBookingsByIdRescheduleResponses];

export type PutOrganizationsByOrgIdBookingsByIdStatusData = {
    /**
     * Новый статус
     */
    body: InternalHandlerUpdateBookingStatusRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID бронирования
         */
        id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/bookings/{id}/status';
};

export type PutOrganizationsByOrgIdBookingsByIdStatusErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PutOrganizationsByOrgIdBookingsByIdStatusError = PutOrganizationsByOrgIdBookingsByIdStatusErrors[keyof PutOrganizationsByOrgIdBookingsByIdStatusErrors];

export type PutOrganizationsByOrgIdBookingsByIdStatusResponses = {
    /**
     * OK
     */
    200: InternalHandlerBookingWrap;
};

export type PutOrganizationsByOrgIdBookingsByIdStatusResponse = PutOrganizationsByOrgIdBookingsByIdStatusResponses[keyof PutOrganizationsByOrgIdBookingsByIdStatusResponses];

export type GetOrganizationsByOrgIdMastersData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters';
};

export type GetOrganizationsByOrgIdMastersErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdMastersError = GetOrganizationsByOrgIdMastersErrors[keyof GetOrganizationsByOrgIdMastersErrors];

export type GetOrganizationsByOrgIdMastersResponses = {
    /**
     * OK
     */
    200: InternalHandlerMastersListWrap;
};

export type GetOrganizationsByOrgIdMastersResponse = GetOrganizationsByOrgIdMastersResponses[keyof GetOrganizationsByOrgIdMastersResponses];

export type PostOrganizationsByOrgIdMastersData = {
    /**
     * Данные мастера
     */
    body: InternalHandlerCreateMasterRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters';
};

export type PostOrganizationsByOrgIdMastersErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdMastersError = PostOrganizationsByOrgIdMastersErrors[keyof PostOrganizationsByOrgIdMastersErrors];

export type PostOrganizationsByOrgIdMastersResponses = {
    /**
     * Created
     */
    201: InternalHandlerMasterWrap;
};

export type PostOrganizationsByOrgIdMastersResponse = PostOrganizationsByOrgIdMastersResponses[keyof PostOrganizationsByOrgIdMastersResponses];

export type GetOrganizationsByOrgIdMastersByMasterIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}';
};

export type GetOrganizationsByOrgIdMastersByMasterIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdMastersByMasterIdError = GetOrganizationsByOrgIdMastersByMasterIdErrors[keyof GetOrganizationsByOrgIdMastersByMasterIdErrors];

export type GetOrganizationsByOrgIdMastersByMasterIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerMasterResponse;
};

export type GetOrganizationsByOrgIdMastersByMasterIdResponse = GetOrganizationsByOrgIdMastersByMasterIdResponses[keyof GetOrganizationsByOrgIdMastersByMasterIdResponses];

export type PutOrganizationsByOrgIdMastersByMasterIdData = {
    /**
     * Обновленные данные мастера
     */
    body: InternalHandlerUpdateMasterRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}';
};

export type PutOrganizationsByOrgIdMastersByMasterIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PutOrganizationsByOrgIdMastersByMasterIdError = PutOrganizationsByOrgIdMastersByMasterIdErrors[keyof PutOrganizationsByOrgIdMastersByMasterIdErrors];

export type PutOrganizationsByOrgIdMastersByMasterIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerMasterWrap;
};

export type PutOrganizationsByOrgIdMastersByMasterIdResponse = PutOrganizationsByOrgIdMastersByMasterIdResponses[keyof PutOrganizationsByOrgIdMastersByMasterIdResponses];

export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
        /**
         * ID салона
         */
        salon_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}/salons/{salon_id}';
};

export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdError = DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdErrors[keyof DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdErrors];

export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
        /**
         * ID салона
         */
        salon_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}/salons/{salon_id}';
};

export type PostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdError = PostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdErrors[keyof PostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdErrors];

export type PostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
        /**
         * ID салона
         */
        salon_id: number;
    };
    query?: {
        /**
         * Начальная дата YYYY-MM-DD
         */
        from?: string;
        /**
         * Конечная дата YYYY-MM-DD
         */
        to?: string;
    };
    url: '/organizations/{org_id}/masters/{master_id}/salons/{salon_id}/schedule-exceptions';
};

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsError = GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsErrors[keyof GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsErrors];

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsResponses = {
    /**
     * OK
     */
    200: InternalHandlerScheduleExceptionsListWrap;
};

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsResponse = GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsResponses[keyof GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsResponses];

export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateData = {
    /**
     * Длительность слота для восстановления
     */
    body: InternalHandlerDeleteExceptionRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
        /**
         * ID салона
         */
        salon_id: number;
        /**
         * Дата в формате YYYY-MM-DD
         */
        date: string;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}/salons/{salon_id}/schedule-exceptions/{date}';
};

export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateError = DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateErrors[keyof DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateErrors];

export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateData = {
    /**
     * Параметры исключения
     */
    body: InternalHandlerScheduleExceptionRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
        /**
         * ID салона
         */
        salon_id: number;
        /**
         * Дата в формате YYYY-MM-DD
         */
        date: string;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}/salons/{salon_id}/schedule-exceptions/{date}';
};

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateError = PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateErrors[keyof PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateErrors];

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateResponses = {
    /**
     * OK
     */
    200: InternalHandlerScheduleExceptionWrap;
};

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateResponse = PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateResponses[keyof PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateResponses];

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
        /**
         * ID салона
         */
        salon_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}/salons/{salon_id}/work-schedule';
};

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleError = GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleErrors[keyof GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleErrors];

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleResponses = {
    /**
     * OK
     */
    200: InternalHandlerWorkSchedulesListWrap;
};

export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleResponse = GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleResponses[keyof GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleResponses];

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleData = {
    /**
     * Расписание и длительность слота
     */
    body: InternalHandlerSetWorkScheduleRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
        /**
         * ID салона
         */
        salon_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}/salons/{salon_id}/work-schedule';
};

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleError = PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleErrors[keyof PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleErrors];

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleResponses = {
    /**
     * OK
     */
    200: InternalHandlerSetWorkScheduleResponseWrap;
};

export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleResponse = PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleResponses[keyof PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleResponses];

export type DeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
        /**
         * ID услуги
         */
        service_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}/services/{service_id}';
};

export type DeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdError = DeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdErrors[keyof DeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdErrors];

export type DeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID мастера
         */
        master_id: number;
        /**
         * ID услуги
         */
        service_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/masters/{master_id}/services/{service_id}';
};

export type PostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdError = PostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdErrors[keyof PostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdErrors];

export type PostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetOrganizationsByOrgIdMembersData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/members';
};

export type GetOrganizationsByOrgIdMembersErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdMembersError = GetOrganizationsByOrgIdMembersErrors[keyof GetOrganizationsByOrgIdMembersErrors];

export type GetOrganizationsByOrgIdMembersResponses = {
    /**
     * OK
     */
    200: InternalHandlerOrgMembersListWrap;
};

export type GetOrganizationsByOrgIdMembersResponse = GetOrganizationsByOrgIdMembersResponses[keyof GetOrganizationsByOrgIdMembersResponses];

export type PostOrganizationsByOrgIdMembersData = {
    /**
     * Данные участника
     */
    body: InternalHandlerAddOrgMemberRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/members';
};

export type PostOrganizationsByOrgIdMembersErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdMembersError = PostOrganizationsByOrgIdMembersErrors[keyof PostOrganizationsByOrgIdMembersErrors];

export type PostOrganizationsByOrgIdMembersResponses = {
    /**
     * Created
     */
    201: InternalHandlerOrgMemberWrap;
};

export type PostOrganizationsByOrgIdMembersResponse = PostOrganizationsByOrgIdMembersResponses[keyof PostOrganizationsByOrgIdMembersResponses];

export type DeleteOrganizationsByOrgIdMembersByVkIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * VK ID участника
         */
        vk_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/members/{vk_id}';
};

export type DeleteOrganizationsByOrgIdMembersByVkIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeleteOrganizationsByOrgIdMembersByVkIdError = DeleteOrganizationsByOrgIdMembersByVkIdErrors[keyof DeleteOrganizationsByOrgIdMembersByVkIdErrors];

export type DeleteOrganizationsByOrgIdMembersByVkIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetOrganizationsByOrgIdRolesData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/roles';
};

export type GetOrganizationsByOrgIdRolesErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdRolesError = GetOrganizationsByOrgIdRolesErrors[keyof GetOrganizationsByOrgIdRolesErrors];

export type GetOrganizationsByOrgIdRolesResponses = {
    /**
     * OK
     */
    200: InternalHandlerOrgRolesListWrap;
};

export type GetOrganizationsByOrgIdRolesResponse = GetOrganizationsByOrgIdRolesResponses[keyof GetOrganizationsByOrgIdRolesResponses];

export type PostOrganizationsByOrgIdRolesData = {
    /**
     * Название роли и permissions
     */
    body: InternalHandlerCreateOrgRoleRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/roles';
};

export type PostOrganizationsByOrgIdRolesErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdRolesError = PostOrganizationsByOrgIdRolesErrors[keyof PostOrganizationsByOrgIdRolesErrors];

export type PostOrganizationsByOrgIdRolesResponses = {
    /**
     * Created
     */
    201: InternalHandlerOrgRoleWrap;
};

export type PostOrganizationsByOrgIdRolesResponse = PostOrganizationsByOrgIdRolesResponses[keyof PostOrganizationsByOrgIdRolesResponses];

export type DeleteOrganizationsByOrgIdRolesByRoleIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID роли
         */
        role_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/roles/{role_id}';
};

export type DeleteOrganizationsByOrgIdRolesByRoleIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeleteOrganizationsByOrgIdRolesByRoleIdError = DeleteOrganizationsByOrgIdRolesByRoleIdErrors[keyof DeleteOrganizationsByOrgIdRolesByRoleIdErrors];

export type DeleteOrganizationsByOrgIdRolesByRoleIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PutOrganizationsByOrgIdRolesByRoleIdData = {
    /**
     * Новое название и/или permissions
     */
    body: InternalHandlerUpdateOrgRoleRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID роли
         */
        role_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/roles/{role_id}';
};

export type PutOrganizationsByOrgIdRolesByRoleIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PutOrganizationsByOrgIdRolesByRoleIdError = PutOrganizationsByOrgIdRolesByRoleIdErrors[keyof PutOrganizationsByOrgIdRolesByRoleIdErrors];

export type PutOrganizationsByOrgIdRolesByRoleIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerOrgRoleWrap;
};

export type PutOrganizationsByOrgIdRolesByRoleIdResponse = PutOrganizationsByOrgIdRolesByRoleIdResponses[keyof PutOrganizationsByOrgIdRolesByRoleIdResponses];

export type GetOrganizationsByOrgIdSalonsData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/salons';
};

export type GetOrganizationsByOrgIdSalonsErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdSalonsError = GetOrganizationsByOrgIdSalonsErrors[keyof GetOrganizationsByOrgIdSalonsErrors];

export type GetOrganizationsByOrgIdSalonsResponses = {
    /**
     * OK
     */
    200: InternalHandlerSalonsListWrap;
};

export type GetOrganizationsByOrgIdSalonsResponse = GetOrganizationsByOrgIdSalonsResponses[keyof GetOrganizationsByOrgIdSalonsResponses];

export type PostOrganizationsByOrgIdSalonsData = {
    /**
     * Данные салона
     */
    body: InternalHandlerCreateSalonRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/salons';
};

export type PostOrganizationsByOrgIdSalonsErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdSalonsError = PostOrganizationsByOrgIdSalonsErrors[keyof PostOrganizationsByOrgIdSalonsErrors];

export type PostOrganizationsByOrgIdSalonsResponses = {
    /**
     * Created
     */
    201: InternalHandlerSalonWrap;
};

export type PostOrganizationsByOrgIdSalonsResponse = PostOrganizationsByOrgIdSalonsResponses[keyof PostOrganizationsByOrgIdSalonsResponses];

export type DeleteOrganizationsByOrgIdSalonsBySalonIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID салона
         */
        salon_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/salons/{salon_id}';
};

export type DeleteOrganizationsByOrgIdSalonsBySalonIdErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeleteOrganizationsByOrgIdSalonsBySalonIdError = DeleteOrganizationsByOrgIdSalonsBySalonIdErrors[keyof DeleteOrganizationsByOrgIdSalonsBySalonIdErrors];

export type DeleteOrganizationsByOrgIdSalonsBySalonIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetOrganizationsByOrgIdSalonsBySalonIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID салона
         */
        salon_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/salons/{salon_id}';
};

export type GetOrganizationsByOrgIdSalonsBySalonIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdSalonsBySalonIdError = GetOrganizationsByOrgIdSalonsBySalonIdErrors[keyof GetOrganizationsByOrgIdSalonsBySalonIdErrors];

export type GetOrganizationsByOrgIdSalonsBySalonIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerSalonResponse;
};

export type GetOrganizationsByOrgIdSalonsBySalonIdResponse = GetOrganizationsByOrgIdSalonsBySalonIdResponses[keyof GetOrganizationsByOrgIdSalonsBySalonIdResponses];

export type PutOrganizationsByOrgIdSalonsBySalonIdData = {
    /**
     * Обновленные данные салона
     */
    body: InternalHandlerUpdateSalonRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID салона
         */
        salon_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/salons/{salon_id}';
};

export type PutOrganizationsByOrgIdSalonsBySalonIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PutOrganizationsByOrgIdSalonsBySalonIdError = PutOrganizationsByOrgIdSalonsBySalonIdErrors[keyof PutOrganizationsByOrgIdSalonsBySalonIdErrors];

export type PutOrganizationsByOrgIdSalonsBySalonIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerSalonWrap;
};

export type PutOrganizationsByOrgIdSalonsBySalonIdResponse = PutOrganizationsByOrgIdSalonsBySalonIdResponses[keyof PutOrganizationsByOrgIdSalonsBySalonIdResponses];

export type DeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID филиала
         */
        salon_id: number;
        /**
         * ID услуги
         */
        service_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/salons/{salon_id}/excluded-services/{service_id}';
};

export type DeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdError = DeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdErrors[keyof DeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdErrors];

export type DeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID филиала
         */
        salon_id: number;
        /**
         * ID услуги
         */
        service_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/salons/{salon_id}/excluded-services/{service_id}';
};

export type PostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdError = PostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdErrors[keyof PostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdErrors];

export type PostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostOrganizationsByOrgIdSalonsBySalonIdPhonesData = {
    /**
     * Номер телефона
     */
    body: InternalHandlerAddSalonPhoneRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID филиала
         */
        salon_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/salons/{salon_id}/phones';
};

export type PostOrganizationsByOrgIdSalonsBySalonIdPhonesErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdSalonsBySalonIdPhonesError = PostOrganizationsByOrgIdSalonsBySalonIdPhonesErrors[keyof PostOrganizationsByOrgIdSalonsBySalonIdPhonesErrors];

export type PostOrganizationsByOrgIdSalonsBySalonIdPhonesResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type DeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID филиала
         */
        salon_id: number;
        /**
         * Номер телефона (URL-encoded)
         */
        phone: string;
    };
    query?: never;
    url: '/organizations/{org_id}/salons/{salon_id}/phones/{phone}';
};

export type DeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneError = DeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneErrors[keyof DeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneErrors];

export type DeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetOrganizationsByOrgIdSalonsBySalonIdServicesData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID салона
         */
        salon_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/salons/{salon_id}/services';
};

export type GetOrganizationsByOrgIdSalonsBySalonIdServicesErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdSalonsBySalonIdServicesError = GetOrganizationsByOrgIdSalonsBySalonIdServicesErrors[keyof GetOrganizationsByOrgIdSalonsBySalonIdServicesErrors];

export type GetOrganizationsByOrgIdSalonsBySalonIdServicesResponses = {
    /**
     * OK
     */
    200: InternalHandlerServicesListWrap;
};

export type GetOrganizationsByOrgIdSalonsBySalonIdServicesResponse = GetOrganizationsByOrgIdSalonsBySalonIdServicesResponses[keyof GetOrganizationsByOrgIdSalonsBySalonIdServicesResponses];

export type GetOrganizationsByOrgIdServicesData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/services';
};

export type GetOrganizationsByOrgIdServicesErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdServicesError = GetOrganizationsByOrgIdServicesErrors[keyof GetOrganizationsByOrgIdServicesErrors];

export type GetOrganizationsByOrgIdServicesResponses = {
    /**
     * OK
     */
    200: InternalHandlerServicesListWrap;
};

export type GetOrganizationsByOrgIdServicesResponse = GetOrganizationsByOrgIdServicesResponses[keyof GetOrganizationsByOrgIdServicesResponses];

export type PostOrganizationsByOrgIdServicesData = {
    /**
     * Данные услуги
     */
    body: InternalHandlerCreateServiceRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/services';
};

export type PostOrganizationsByOrgIdServicesErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdServicesError = PostOrganizationsByOrgIdServicesErrors[keyof PostOrganizationsByOrgIdServicesErrors];

export type PostOrganizationsByOrgIdServicesResponses = {
    /**
     * Created
     */
    201: InternalHandlerServiceWrap;
};

export type PostOrganizationsByOrgIdServicesResponse = PostOrganizationsByOrgIdServicesResponses[keyof PostOrganizationsByOrgIdServicesResponses];

export type PutOrganizationsByOrgIdServicesByIdData = {
    /**
     * Обновленные данные услуги
     */
    body: InternalHandlerUpdateServiceRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * ID услуги
         */
        id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/services/{id}';
};

export type PutOrganizationsByOrgIdServicesByIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PutOrganizationsByOrgIdServicesByIdError = PutOrganizationsByOrgIdServicesByIdErrors[keyof PutOrganizationsByOrgIdServicesByIdErrors];

export type PutOrganizationsByOrgIdServicesByIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerServiceWrap;
};

export type PutOrganizationsByOrgIdServicesByIdResponse = PutOrganizationsByOrgIdServicesByIdResponses[keyof PutOrganizationsByOrgIdServicesByIdResponses];

export type GetOrganizationsByOrgIdSlotsData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: {
        /**
         * ID услуги
         */
        service_id?: number;
        /**
         * Дата (YYYY-MM-DD)
         */
        date?: string;
        /**
         * Статус слота (AVAILABLE, RESERVED, BOOKED, CANCELLED)
         */
        status?: string;
    };
    url: '/organizations/{org_id}/slots';
};

export type GetOrganizationsByOrgIdSlotsErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetOrganizationsByOrgIdSlotsError = GetOrganizationsByOrgIdSlotsErrors[keyof GetOrganizationsByOrgIdSlotsErrors];

export type GetOrganizationsByOrgIdSlotsResponses = {
    /**
     * OK
     */
    200: InternalHandlerSlotsListWrap;
};

export type GetOrganizationsByOrgIdSlotsResponse = GetOrganizationsByOrgIdSlotsResponses[keyof GetOrganizationsByOrgIdSlotsResponses];

export type PostOrganizationsByOrgIdSlotsGenerateData = {
    /**
     * Массив интервалов для генерации слотов
     */
    body: Array<InternalHandlerGenerateSlotInterval>;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/slots/generate';
};

export type PostOrganizationsByOrgIdSlotsGenerateErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostOrganizationsByOrgIdSlotsGenerateError = PostOrganizationsByOrgIdSlotsGenerateErrors[keyof PostOrganizationsByOrgIdSlotsGenerateErrors];

export type PostOrganizationsByOrgIdSlotsGenerateResponses = {
    /**
     * Created
     */
    201: InternalHandlerSlotsListWrap;
};

export type PostOrganizationsByOrgIdSlotsGenerateResponse = PostOrganizationsByOrgIdSlotsGenerateResponses[keyof PostOrganizationsByOrgIdSlotsGenerateResponses];

export type GetOrganizationsByOrgIdTreeYearsData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/organizations/{org_id}/tree/years';
};

export type GetOrganizationsByOrgIdTreeYearsErrors = {
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetOrganizationsByOrgIdTreeYearsError = GetOrganizationsByOrgIdTreeYearsErrors[keyof GetOrganizationsByOrgIdTreeYearsErrors];

export type GetOrganizationsByOrgIdTreeYearsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOrganizationsByOrgIdTreeYearsResponse = GetOrganizationsByOrgIdTreeYearsResponses[keyof GetOrganizationsByOrgIdTreeYearsResponses];

export type GetOrganizationsByOrgIdTreeYearsByYMonthsData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * Год
         */
        y: number;
    };
    query?: never;
    url: '/organizations/{org_id}/tree/years/{y}/months';
};

export type GetOrganizationsByOrgIdTreeYearsByYMonthsErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetOrganizationsByOrgIdTreeYearsByYMonthsError = GetOrganizationsByOrgIdTreeYearsByYMonthsErrors[keyof GetOrganizationsByOrgIdTreeYearsByYMonthsErrors];

export type GetOrganizationsByOrgIdTreeYearsByYMonthsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOrganizationsByOrgIdTreeYearsByYMonthsResponse = GetOrganizationsByOrgIdTreeYearsByYMonthsResponses[keyof GetOrganizationsByOrgIdTreeYearsByYMonthsResponses];

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * Год
         */
        y: number;
        /**
         * Месяц
         */
        m: number;
    };
    query?: never;
    url: '/organizations/{org_id}/tree/years/{y}/months/{m}/days';
};

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysError = GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysErrors[keyof GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysErrors];

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysResponse = GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysResponses[keyof GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysResponses];

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
        /**
         * Год
         */
        y: number;
        /**
         * Месяц
         */
        m: number;
        /**
         * День
         */
        d: number;
    };
    query?: never;
    url: '/organizations/{org_id}/tree/years/{y}/months/{m}/days/{d}/slots';
};

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsErrors = {
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsError = GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsErrors[keyof GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsErrors];

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsResponse = GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsResponses[keyof GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsResponses];

export type DeletePublicBookingsByIdData = {
    body?: never;
    path: {
        /**
         * ID бронирования
         */
        id: number;
    };
    query?: never;
    url: '/public/bookings/{id}';
};

export type DeletePublicBookingsByIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Not Found
     */
    404: InternalHandlerErrorResponse;
    /**
     * Conflict
     */
    409: InternalHandlerErrorResponse;
};

export type DeletePublicBookingsByIdError = DeletePublicBookingsByIdErrors[keyof DeletePublicBookingsByIdErrors];

export type DeletePublicBookingsByIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerBookingWrap;
};

export type DeletePublicBookingsByIdResponse = DeletePublicBookingsByIdResponses[keyof DeletePublicBookingsByIdResponses];

export type PutPublicBookingsByIdRescheduleData = {
    /**
     * Решение клиента
     */
    body: InternalHandlerRespondToRescheduleRequest;
    path: {
        /**
         * ID бронирования
         */
        id: number;
    };
    query?: never;
    url: '/public/bookings/{id}/reschedule';
};

export type PutPublicBookingsByIdRescheduleErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Not Found
     */
    404: InternalHandlerErrorResponse;
    /**
     * Conflict
     */
    409: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PutPublicBookingsByIdRescheduleError = PutPublicBookingsByIdRescheduleErrors[keyof PutPublicBookingsByIdRescheduleErrors];

export type PutPublicBookingsByIdRescheduleResponses = {
    /**
     * OK
     */
    200: InternalHandlerBookingWrap;
};

export type PutPublicBookingsByIdRescheduleResponse = PutPublicBookingsByIdRescheduleResponses[keyof PutPublicBookingsByIdRescheduleResponses];

export type GetPublicBookingsMyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Статус (PENDING, CONFIRMED, REJECTED, CANCELLED)
         */
        status?: string;
    };
    url: '/public/bookings/my';
};

export type GetPublicBookingsMyErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetPublicBookingsMyError = GetPublicBookingsMyErrors[keyof GetPublicBookingsMyErrors];

export type GetPublicBookingsMyResponses = {
    /**
     * OK
     */
    200: InternalHandlerBookingsListWrap;
};

export type GetPublicBookingsMyResponse = GetPublicBookingsMyResponses[keyof GetPublicBookingsMyResponses];

export type PostPublicOrgsByOrgIdBookingsData = {
    /**
     * Данные бронирования
     */
    body: InternalHandlerCreatePublicBookingRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/public/orgs/{org_id}/bookings';
};

export type PostPublicOrgsByOrgIdBookingsErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Not Found
     */
    404: InternalHandlerErrorResponse;
    /**
     * Conflict
     */
    409: InternalHandlerErrorResponse;
};

export type PostPublicOrgsByOrgIdBookingsError = PostPublicOrgsByOrgIdBookingsErrors[keyof PostPublicOrgsByOrgIdBookingsErrors];

export type PostPublicOrgsByOrgIdBookingsResponses = {
    /**
     * Created
     */
    201: InternalHandlerCreateBookingResponse;
};

export type PostPublicOrgsByOrgIdBookingsResponse = PostPublicOrgsByOrgIdBookingsResponses[keyof PostPublicOrgsByOrgIdBookingsResponses];

export type GetPublicOrgsByOrgIdMastersData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/public/orgs/{org_id}/masters';
};

export type GetPublicOrgsByOrgIdMastersErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetPublicOrgsByOrgIdMastersError = GetPublicOrgsByOrgIdMastersErrors[keyof GetPublicOrgsByOrgIdMastersErrors];

export type GetPublicOrgsByOrgIdMastersResponses = {
    /**
     * OK
     */
    200: InternalHandlerMastersListWrap;
};

export type GetPublicOrgsByOrgIdMastersResponse = GetPublicOrgsByOrgIdMastersResponses[keyof GetPublicOrgsByOrgIdMastersResponses];

export type GetPublicOrgsByOrgIdServicesData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: {
        /**
         * ID салона для фильтрации
         */
        salon_id?: number;
    };
    url: '/public/orgs/{org_id}/services';
};

export type GetPublicOrgsByOrgIdServicesErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetPublicOrgsByOrgIdServicesError = GetPublicOrgsByOrgIdServicesErrors[keyof GetPublicOrgsByOrgIdServicesErrors];

export type GetPublicOrgsByOrgIdServicesResponses = {
    /**
     * OK
     */
    200: InternalHandlerServicesListWrap;
};

export type GetPublicOrgsByOrgIdServicesResponse = GetPublicOrgsByOrgIdServicesResponses[keyof GetPublicOrgsByOrgIdServicesResponses];

export type GetPublicOrgsByOrgIdSlotsData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: {
        /**
         * Дата (YYYY-MM-DD)
         */
        date?: string;
    };
    url: '/public/orgs/{org_id}/slots';
};

export type GetPublicOrgsByOrgIdSlotsErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetPublicOrgsByOrgIdSlotsError = GetPublicOrgsByOrgIdSlotsErrors[keyof GetPublicOrgsByOrgIdSlotsErrors];

export type GetPublicOrgsByOrgIdSlotsResponses = {
    /**
     * OK
     */
    200: InternalHandlerSlotsListWrap;
};

export type GetPublicOrgsByOrgIdSlotsResponse = GetPublicOrgsByOrgIdSlotsResponses[keyof GetPublicOrgsByOrgIdSlotsResponses];

export type GetPublicOrgsByOrgIdSlotsWindowsData = {
    body?: never;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query: {
        /**
         * Продолжительность услуги (минуты)
         */
        service_duration_min: number;
        /**
         * Дата (YYYY-MM-DD)
         */
        date?: string;
        /**
         * ID мастера
         */
        master_id?: number;
        /**
         * ID салона
         */
        salon_id?: number;
    };
    url: '/public/orgs/{org_id}/slots/windows';
};

export type GetPublicOrgsByOrgIdSlotsWindowsErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetPublicOrgsByOrgIdSlotsWindowsError = GetPublicOrgsByOrgIdSlotsWindowsErrors[keyof GetPublicOrgsByOrgIdSlotsWindowsErrors];

export type GetPublicOrgsByOrgIdSlotsWindowsResponses = {
    /**
     * OK
     */
    200: InternalHandlerAvailableWindowsListWrap;
};

export type GetPublicOrgsByOrgIdSlotsWindowsResponse = GetPublicOrgsByOrgIdSlotsWindowsResponses[keyof GetPublicOrgsByOrgIdSlotsWindowsResponses];

export type PostPublicOrgsByOrgIdWaitlistData = {
    /**
     * Параметры записи в лист ожидания
     */
    body: InternalHandlerJoinWaitlistRequest;
    path: {
        /**
         * ID организации
         */
        org_id: number;
    };
    query?: never;
    url: '/public/orgs/{org_id}/waitlist';
};

export type PostPublicOrgsByOrgIdWaitlistErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Not Found
     */
    404: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostPublicOrgsByOrgIdWaitlistError = PostPublicOrgsByOrgIdWaitlistErrors[keyof PostPublicOrgsByOrgIdWaitlistErrors];

export type PostPublicOrgsByOrgIdWaitlistResponses = {
    /**
     * Created
     */
    201: InternalHandlerWaitlistEntryWrap;
};

export type PostPublicOrgsByOrgIdWaitlistResponse = PostPublicOrgsByOrgIdWaitlistResponses[keyof PostPublicOrgsByOrgIdWaitlistResponses];

export type GetPublicSearchServicesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Поисковый запрос
         */
        q: string;
        /**
         * Лимит результатов
         */
        limit?: number;
        /**
         * Смещение
         */
        offset?: number;
    };
    url: '/public/search/services';
};

export type GetPublicSearchServicesErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetPublicSearchServicesError = GetPublicSearchServicesErrors[keyof GetPublicSearchServicesErrors];

export type GetPublicSearchServicesResponses = {
    /**
     * OK
     */
    200: InternalHandlerSearchServicesResponse;
};

export type GetPublicSearchServicesResponse = GetPublicSearchServicesResponses[keyof GetPublicSearchServicesResponses];

export type DeletePublicWaitlistByIdData = {
    body?: never;
    path: {
        /**
         * ID записи в листе ожидания
         */
        id: number;
    };
    query?: never;
    url: '/public/waitlist/{id}';
};

export type DeletePublicWaitlistByIdErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Not Found
     */
    404: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type DeletePublicWaitlistByIdError = DeletePublicWaitlistByIdErrors[keyof DeletePublicWaitlistByIdErrors];

export type DeletePublicWaitlistByIdResponses = {
    /**
     * OK
     */
    200: InternalHandlerWaitlistEntryWrap;
};

export type DeletePublicWaitlistByIdResponse = DeletePublicWaitlistByIdResponses[keyof DeletePublicWaitlistByIdResponses];

export type PostPublicWaitlistByIdConfirmData = {
    body?: never;
    path: {
        /**
         * ID записи в листе ожидания
         */
        id: number;
    };
    query?: never;
    url: '/public/waitlist/{id}/confirm';
};

export type PostPublicWaitlistByIdConfirmErrors = {
    /**
     * Bad Request
     */
    400: InternalHandlerErrorResponse;
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Forbidden
     */
    403: InternalHandlerErrorResponse;
    /**
     * Not Found
     */
    404: InternalHandlerErrorResponse;
    /**
     * Conflict
     */
    409: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type PostPublicWaitlistByIdConfirmError = PostPublicWaitlistByIdConfirmErrors[keyof PostPublicWaitlistByIdConfirmErrors];

export type PostPublicWaitlistByIdConfirmResponses = {
    /**
     * OK
     */
    200: InternalHandlerConfirmWaitlistSlotResponse;
};

export type PostPublicWaitlistByIdConfirmResponse = PostPublicWaitlistByIdConfirmResponses[keyof PostPublicWaitlistByIdConfirmResponses];

export type GetPublicWaitlistMyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public/waitlist/my';
};

export type GetPublicWaitlistMyErrors = {
    /**
     * Unauthorized
     */
    401: InternalHandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: InternalHandlerErrorResponse;
};

export type GetPublicWaitlistMyError = GetPublicWaitlistMyErrors[keyof GetPublicWaitlistMyErrors];

export type GetPublicWaitlistMyResponses = {
    /**
     * OK
     */
    200: InternalHandlerWaitlistEntriesListWrap;
};

export type GetPublicWaitlistMyResponse = GetPublicWaitlistMyResponses[keyof GetPublicWaitlistMyResponses];
