// generated with @7nohe/openapi-react-query-codegen@2.1.0 

import { UseQueryResult } from "@tanstack/react-query";
import type { Options } from "../requests/sdk.gen";
import { deleteOrganizationsByOrgIdBookingsByIdReschedule, deleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonId, deleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDate, deleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceId, deleteOrganizationsByOrgIdMembersByVkId, deleteOrganizationsByOrgIdRolesByRoleId, deleteOrganizationsByOrgIdSalonsBySalonId, deleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceId, deleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhone, deletePublicBookingsById, deletePublicWaitlistById, getHealth, getMeContext, getOrganizationsByOrgId, getOrganizationsByOrgIdBookings, getOrganizationsByOrgIdMasters, getOrganizationsByOrgIdMastersByMasterId, getOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptions, getOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkSchedule, getOrganizationsByOrgIdMembers, getOrganizationsByOrgIdRoles, getOrganizationsByOrgIdSalons, getOrganizationsByOrgIdSalonsBySalonId, getOrganizationsByOrgIdSalonsBySalonIdServices, getOrganizationsByOrgIdServices, getOrganizationsByOrgIdSlots, getOrganizationsByOrgIdTreeYears, getOrganizationsByOrgIdTreeYearsByYMonths, getOrganizationsByOrgIdTreeYearsByYMonthsByMDays, getOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlots, getPublicBookingsMy, getPublicOrgsByOrgIdMasters, getPublicOrgsByOrgIdServices, getPublicOrgsByOrgIdSlots, getPublicOrgsByOrgIdSlotsWindows, getPublicSearchServices, getPublicWaitlistMy, patchOrganizationsByOrgIdBookingsByIdDuration, postOrganizations, postOrganizationsByOrgIdBookings, postOrganizationsByOrgIdBookingsByIdReschedule, postOrganizationsByOrgIdMasters, postOrganizationsByOrgIdMastersByMasterIdSalonsBySalonId, postOrganizationsByOrgIdMastersByMasterIdServicesByServiceId, postOrganizationsByOrgIdMembers, postOrganizationsByOrgIdRoles, postOrganizationsByOrgIdSalons, postOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceId, postOrganizationsByOrgIdSalonsBySalonIdPhones, postOrganizationsByOrgIdServices, postOrganizationsByOrgIdSlotsGenerate, postPublicOrgsByOrgIdBookings, postPublicOrgsByOrgIdWaitlist, postPublicWaitlistByIdConfirm, putOrganizationsByOrgId, putOrganizationsByOrgIdBookingsByIdStatus, putOrganizationsByOrgIdMastersByMasterId, putOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDate, putOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkSchedule, putOrganizationsByOrgIdRolesByRoleId, putOrganizationsByOrgIdSalonsBySalonId, putOrganizationsByOrgIdServicesById, putPublicBookingsByIdReschedule } from "../requests/sdk.gen";
import { GetHealthData, GetMeContextData, GetOrganizationsByOrgIdBookingsData, GetOrganizationsByOrgIdData, GetOrganizationsByOrgIdMastersByMasterIdData, GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsData, GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleData, GetOrganizationsByOrgIdMastersData, GetOrganizationsByOrgIdMembersData, GetOrganizationsByOrgIdRolesData, GetOrganizationsByOrgIdSalonsBySalonIdData, GetOrganizationsByOrgIdSalonsBySalonIdServicesData, GetOrganizationsByOrgIdSalonsData, GetOrganizationsByOrgIdServicesData, GetOrganizationsByOrgIdSlotsData, GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsData, GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysData, GetOrganizationsByOrgIdTreeYearsByYMonthsData, GetOrganizationsByOrgIdTreeYearsData, GetPublicBookingsMyData, GetPublicOrgsByOrgIdMastersData, GetPublicOrgsByOrgIdServicesData, GetPublicOrgsByOrgIdSlotsData, GetPublicOrgsByOrgIdSlotsWindowsData, GetPublicSearchServicesData, GetPublicWaitlistMyData } from "../requests/types.gen";
export type GetHealthDefaultResponse = Awaited<ReturnType<typeof getHealth>>["data"];
export type GetHealthQueryResult<TData = GetHealthDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetHealthKey = "GetHealth";
export const UseGetHealthKeyFn = (clientOptions: Options<GetHealthData, true> = {}, queryKey?: Array<unknown>) => [useGetHealthKey, ...(queryKey ?? [clientOptions])];
export type GetMeContextDefaultResponse = Awaited<ReturnType<typeof getMeContext>>["data"];
export type GetMeContextQueryResult<TData = GetMeContextDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetMeContextKey = "GetMeContext";
export const UseGetMeContextKeyFn = (clientOptions: Options<GetMeContextData, true> = {}, queryKey?: Array<unknown>) => [useGetMeContextKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgId>>["data"];
export type GetOrganizationsByOrgIdQueryResult<TData = GetOrganizationsByOrgIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdKey = "GetOrganizationsByOrgId";
export const UseGetOrganizationsByOrgIdKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdBookingsDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdBookings>>["data"];
export type GetOrganizationsByOrgIdBookingsQueryResult<TData = GetOrganizationsByOrgIdBookingsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdBookingsKey = "GetOrganizationsByOrgIdBookings";
export const UseGetOrganizationsByOrgIdBookingsKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdBookingsData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdBookingsKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdMastersDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdMasters>>["data"];
export type GetOrganizationsByOrgIdMastersQueryResult<TData = GetOrganizationsByOrgIdMastersDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdMastersKey = "GetOrganizationsByOrgIdMasters";
export const UseGetOrganizationsByOrgIdMastersKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdMastersData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdMastersKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdMastersByMasterIdDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdMastersByMasterId>>["data"];
export type GetOrganizationsByOrgIdMastersByMasterIdQueryResult<TData = GetOrganizationsByOrgIdMastersByMasterIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdMastersByMasterIdKey = "GetOrganizationsByOrgIdMastersByMasterId";
export const UseGetOrganizationsByOrgIdMastersByMasterIdKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdMastersByMasterIdData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdMastersByMasterIdKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptions>>["data"];
export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsQueryResult<TData = GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsKey = "GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptions";
export const UseGetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkSchedule>>["data"];
export type GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleQueryResult<TData = GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleKey = "GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkSchedule";
export const UseGetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdMembersDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdMembers>>["data"];
export type GetOrganizationsByOrgIdMembersQueryResult<TData = GetOrganizationsByOrgIdMembersDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdMembersKey = "GetOrganizationsByOrgIdMembers";
export const UseGetOrganizationsByOrgIdMembersKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdMembersData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdMembersKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdRolesDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdRoles>>["data"];
export type GetOrganizationsByOrgIdRolesQueryResult<TData = GetOrganizationsByOrgIdRolesDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdRolesKey = "GetOrganizationsByOrgIdRoles";
export const UseGetOrganizationsByOrgIdRolesKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdRolesData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdRolesKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdSalonsDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdSalons>>["data"];
export type GetOrganizationsByOrgIdSalonsQueryResult<TData = GetOrganizationsByOrgIdSalonsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdSalonsKey = "GetOrganizationsByOrgIdSalons";
export const UseGetOrganizationsByOrgIdSalonsKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdSalonsData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdSalonsKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdSalonsBySalonIdDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdSalonsBySalonId>>["data"];
export type GetOrganizationsByOrgIdSalonsBySalonIdQueryResult<TData = GetOrganizationsByOrgIdSalonsBySalonIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdSalonsBySalonIdKey = "GetOrganizationsByOrgIdSalonsBySalonId";
export const UseGetOrganizationsByOrgIdSalonsBySalonIdKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdSalonsBySalonIdData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdSalonsBySalonIdKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdSalonsBySalonIdServicesDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdSalonsBySalonIdServices>>["data"];
export type GetOrganizationsByOrgIdSalonsBySalonIdServicesQueryResult<TData = GetOrganizationsByOrgIdSalonsBySalonIdServicesDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdSalonsBySalonIdServicesKey = "GetOrganizationsByOrgIdSalonsBySalonIdServices";
export const UseGetOrganizationsByOrgIdSalonsBySalonIdServicesKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdSalonsBySalonIdServicesData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdSalonsBySalonIdServicesKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdServicesDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdServices>>["data"];
export type GetOrganizationsByOrgIdServicesQueryResult<TData = GetOrganizationsByOrgIdServicesDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdServicesKey = "GetOrganizationsByOrgIdServices";
export const UseGetOrganizationsByOrgIdServicesKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdServicesData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdServicesKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdSlotsDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdSlots>>["data"];
export type GetOrganizationsByOrgIdSlotsQueryResult<TData = GetOrganizationsByOrgIdSlotsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdSlotsKey = "GetOrganizationsByOrgIdSlots";
export const UseGetOrganizationsByOrgIdSlotsKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdSlotsData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdSlotsKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdTreeYearsDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdTreeYears>>["data"];
export type GetOrganizationsByOrgIdTreeYearsQueryResult<TData = GetOrganizationsByOrgIdTreeYearsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdTreeYearsKey = "GetOrganizationsByOrgIdTreeYears";
export const UseGetOrganizationsByOrgIdTreeYearsKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdTreeYearsData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdTreeYearsKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdTreeYearsByYMonthsDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdTreeYearsByYMonths>>["data"];
export type GetOrganizationsByOrgIdTreeYearsByYMonthsQueryResult<TData = GetOrganizationsByOrgIdTreeYearsByYMonthsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdTreeYearsByYMonthsKey = "GetOrganizationsByOrgIdTreeYearsByYMonths";
export const UseGetOrganizationsByOrgIdTreeYearsByYMonthsKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdTreeYearsByYMonthsData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdTreeYearsByYMonthsKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdTreeYearsByYMonthsByMDays>>["data"];
export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysQueryResult<TData = GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysKey = "GetOrganizationsByOrgIdTreeYearsByYMonthsByMDays";
export const UseGetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysKey, ...(queryKey ?? [clientOptions])];
export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsDefaultResponse = Awaited<ReturnType<typeof getOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlots>>["data"];
export type GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsQueryResult<TData = GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsKey = "GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlots";
export const UseGetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsKeyFn = (clientOptions: Options<GetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsData, true>, queryKey?: Array<unknown>) => [useGetOrganizationsByOrgIdTreeYearsByYMonthsByMDaysByDSlotsKey, ...(queryKey ?? [clientOptions])];
export type GetPublicBookingsMyDefaultResponse = Awaited<ReturnType<typeof getPublicBookingsMy>>["data"];
export type GetPublicBookingsMyQueryResult<TData = GetPublicBookingsMyDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetPublicBookingsMyKey = "GetPublicBookingsMy";
export const UseGetPublicBookingsMyKeyFn = (clientOptions: Options<GetPublicBookingsMyData, true> = {}, queryKey?: Array<unknown>) => [useGetPublicBookingsMyKey, ...(queryKey ?? [clientOptions])];
export type GetPublicOrgsByOrgIdMastersDefaultResponse = Awaited<ReturnType<typeof getPublicOrgsByOrgIdMasters>>["data"];
export type GetPublicOrgsByOrgIdMastersQueryResult<TData = GetPublicOrgsByOrgIdMastersDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetPublicOrgsByOrgIdMastersKey = "GetPublicOrgsByOrgIdMasters";
export const UseGetPublicOrgsByOrgIdMastersKeyFn = (clientOptions: Options<GetPublicOrgsByOrgIdMastersData, true>, queryKey?: Array<unknown>) => [useGetPublicOrgsByOrgIdMastersKey, ...(queryKey ?? [clientOptions])];
export type GetPublicOrgsByOrgIdServicesDefaultResponse = Awaited<ReturnType<typeof getPublicOrgsByOrgIdServices>>["data"];
export type GetPublicOrgsByOrgIdServicesQueryResult<TData = GetPublicOrgsByOrgIdServicesDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetPublicOrgsByOrgIdServicesKey = "GetPublicOrgsByOrgIdServices";
export const UseGetPublicOrgsByOrgIdServicesKeyFn = (clientOptions: Options<GetPublicOrgsByOrgIdServicesData, true>, queryKey?: Array<unknown>) => [useGetPublicOrgsByOrgIdServicesKey, ...(queryKey ?? [clientOptions])];
export type GetPublicOrgsByOrgIdSlotsDefaultResponse = Awaited<ReturnType<typeof getPublicOrgsByOrgIdSlots>>["data"];
export type GetPublicOrgsByOrgIdSlotsQueryResult<TData = GetPublicOrgsByOrgIdSlotsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetPublicOrgsByOrgIdSlotsKey = "GetPublicOrgsByOrgIdSlots";
export const UseGetPublicOrgsByOrgIdSlotsKeyFn = (clientOptions: Options<GetPublicOrgsByOrgIdSlotsData, true>, queryKey?: Array<unknown>) => [useGetPublicOrgsByOrgIdSlotsKey, ...(queryKey ?? [clientOptions])];
export type GetPublicOrgsByOrgIdSlotsWindowsDefaultResponse = Awaited<ReturnType<typeof getPublicOrgsByOrgIdSlotsWindows>>["data"];
export type GetPublicOrgsByOrgIdSlotsWindowsQueryResult<TData = GetPublicOrgsByOrgIdSlotsWindowsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetPublicOrgsByOrgIdSlotsWindowsKey = "GetPublicOrgsByOrgIdSlotsWindows";
export const UseGetPublicOrgsByOrgIdSlotsWindowsKeyFn = (clientOptions: Options<GetPublicOrgsByOrgIdSlotsWindowsData, true>, queryKey?: Array<unknown>) => [useGetPublicOrgsByOrgIdSlotsWindowsKey, ...(queryKey ?? [clientOptions])];
export type GetPublicSearchServicesDefaultResponse = Awaited<ReturnType<typeof getPublicSearchServices>>["data"];
export type GetPublicSearchServicesQueryResult<TData = GetPublicSearchServicesDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetPublicSearchServicesKey = "GetPublicSearchServices";
export const UseGetPublicSearchServicesKeyFn = (clientOptions: Options<GetPublicSearchServicesData, true>, queryKey?: Array<unknown>) => [useGetPublicSearchServicesKey, ...(queryKey ?? [clientOptions])];
export type GetPublicWaitlistMyDefaultResponse = Awaited<ReturnType<typeof getPublicWaitlistMy>>["data"];
export type GetPublicWaitlistMyQueryResult<TData = GetPublicWaitlistMyDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetPublicWaitlistMyKey = "GetPublicWaitlistMy";
export const UseGetPublicWaitlistMyKeyFn = (clientOptions: Options<GetPublicWaitlistMyData, true> = {}, queryKey?: Array<unknown>) => [useGetPublicWaitlistMyKey, ...(queryKey ?? [clientOptions])];
export type PostOrganizationsMutationResult = Awaited<ReturnType<typeof postOrganizations>>;
export const usePostOrganizationsKey = "PostOrganizations";
export const UsePostOrganizationsKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdBookingsMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdBookings>>;
export const usePostOrganizationsByOrgIdBookingsKey = "PostOrganizationsByOrgIdBookings";
export const UsePostOrganizationsByOrgIdBookingsKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdBookingsKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdBookingsByIdRescheduleMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdBookingsByIdReschedule>>;
export const usePostOrganizationsByOrgIdBookingsByIdRescheduleKey = "PostOrganizationsByOrgIdBookingsByIdReschedule";
export const UsePostOrganizationsByOrgIdBookingsByIdRescheduleKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdBookingsByIdRescheduleKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdMastersMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdMasters>>;
export const usePostOrganizationsByOrgIdMastersKey = "PostOrganizationsByOrgIdMasters";
export const UsePostOrganizationsByOrgIdMastersKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdMastersKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdMastersByMasterIdSalonsBySalonId>>;
export const usePostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdKey = "PostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonId";
export const UsePostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdMastersByMasterIdServicesByServiceId>>;
export const usePostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdKey = "PostOrganizationsByOrgIdMastersByMasterIdServicesByServiceId";
export const UsePostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdMembersMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdMembers>>;
export const usePostOrganizationsByOrgIdMembersKey = "PostOrganizationsByOrgIdMembers";
export const UsePostOrganizationsByOrgIdMembersKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdMembersKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdRolesMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdRoles>>;
export const usePostOrganizationsByOrgIdRolesKey = "PostOrganizationsByOrgIdRoles";
export const UsePostOrganizationsByOrgIdRolesKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdRolesKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdSalonsMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdSalons>>;
export const usePostOrganizationsByOrgIdSalonsKey = "PostOrganizationsByOrgIdSalons";
export const UsePostOrganizationsByOrgIdSalonsKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdSalonsKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceId>>;
export const usePostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdKey = "PostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceId";
export const UsePostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdSalonsBySalonIdPhonesMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdSalonsBySalonIdPhones>>;
export const usePostOrganizationsByOrgIdSalonsBySalonIdPhonesKey = "PostOrganizationsByOrgIdSalonsBySalonIdPhones";
export const UsePostOrganizationsByOrgIdSalonsBySalonIdPhonesKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdSalonsBySalonIdPhonesKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdServicesMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdServices>>;
export const usePostOrganizationsByOrgIdServicesKey = "PostOrganizationsByOrgIdServices";
export const UsePostOrganizationsByOrgIdServicesKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdServicesKey, ...(mutationKey ?? [])];
export type PostOrganizationsByOrgIdSlotsGenerateMutationResult = Awaited<ReturnType<typeof postOrganizationsByOrgIdSlotsGenerate>>;
export const usePostOrganizationsByOrgIdSlotsGenerateKey = "PostOrganizationsByOrgIdSlotsGenerate";
export const UsePostOrganizationsByOrgIdSlotsGenerateKeyFn = (mutationKey?: Array<unknown>) => [usePostOrganizationsByOrgIdSlotsGenerateKey, ...(mutationKey ?? [])];
export type PostPublicOrgsByOrgIdBookingsMutationResult = Awaited<ReturnType<typeof postPublicOrgsByOrgIdBookings>>;
export const usePostPublicOrgsByOrgIdBookingsKey = "PostPublicOrgsByOrgIdBookings";
export const UsePostPublicOrgsByOrgIdBookingsKeyFn = (mutationKey?: Array<unknown>) => [usePostPublicOrgsByOrgIdBookingsKey, ...(mutationKey ?? [])];
export type PostPublicOrgsByOrgIdWaitlistMutationResult = Awaited<ReturnType<typeof postPublicOrgsByOrgIdWaitlist>>;
export const usePostPublicOrgsByOrgIdWaitlistKey = "PostPublicOrgsByOrgIdWaitlist";
export const UsePostPublicOrgsByOrgIdWaitlistKeyFn = (mutationKey?: Array<unknown>) => [usePostPublicOrgsByOrgIdWaitlistKey, ...(mutationKey ?? [])];
export type PostPublicWaitlistByIdConfirmMutationResult = Awaited<ReturnType<typeof postPublicWaitlistByIdConfirm>>;
export const usePostPublicWaitlistByIdConfirmKey = "PostPublicWaitlistByIdConfirm";
export const UsePostPublicWaitlistByIdConfirmKeyFn = (mutationKey?: Array<unknown>) => [usePostPublicWaitlistByIdConfirmKey, ...(mutationKey ?? [])];
export type PutOrganizationsByOrgIdMutationResult = Awaited<ReturnType<typeof putOrganizationsByOrgId>>;
export const usePutOrganizationsByOrgIdKey = "PutOrganizationsByOrgId";
export const UsePutOrganizationsByOrgIdKeyFn = (mutationKey?: Array<unknown>) => [usePutOrganizationsByOrgIdKey, ...(mutationKey ?? [])];
export type PutOrganizationsByOrgIdBookingsByIdStatusMutationResult = Awaited<ReturnType<typeof putOrganizationsByOrgIdBookingsByIdStatus>>;
export const usePutOrganizationsByOrgIdBookingsByIdStatusKey = "PutOrganizationsByOrgIdBookingsByIdStatus";
export const UsePutOrganizationsByOrgIdBookingsByIdStatusKeyFn = (mutationKey?: Array<unknown>) => [usePutOrganizationsByOrgIdBookingsByIdStatusKey, ...(mutationKey ?? [])];
export type PutOrganizationsByOrgIdMastersByMasterIdMutationResult = Awaited<ReturnType<typeof putOrganizationsByOrgIdMastersByMasterId>>;
export const usePutOrganizationsByOrgIdMastersByMasterIdKey = "PutOrganizationsByOrgIdMastersByMasterId";
export const UsePutOrganizationsByOrgIdMastersByMasterIdKeyFn = (mutationKey?: Array<unknown>) => [usePutOrganizationsByOrgIdMastersByMasterIdKey, ...(mutationKey ?? [])];
export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateMutationResult = Awaited<ReturnType<typeof putOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDate>>;
export const usePutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateKey = "PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDate";
export const UsePutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateKeyFn = (mutationKey?: Array<unknown>) => [usePutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateKey, ...(mutationKey ?? [])];
export type PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleMutationResult = Awaited<ReturnType<typeof putOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkSchedule>>;
export const usePutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleKey = "PutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkSchedule";
export const UsePutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleKeyFn = (mutationKey?: Array<unknown>) => [usePutOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdWorkScheduleKey, ...(mutationKey ?? [])];
export type PutOrganizationsByOrgIdRolesByRoleIdMutationResult = Awaited<ReturnType<typeof putOrganizationsByOrgIdRolesByRoleId>>;
export const usePutOrganizationsByOrgIdRolesByRoleIdKey = "PutOrganizationsByOrgIdRolesByRoleId";
export const UsePutOrganizationsByOrgIdRolesByRoleIdKeyFn = (mutationKey?: Array<unknown>) => [usePutOrganizationsByOrgIdRolesByRoleIdKey, ...(mutationKey ?? [])];
export type PutOrganizationsByOrgIdSalonsBySalonIdMutationResult = Awaited<ReturnType<typeof putOrganizationsByOrgIdSalonsBySalonId>>;
export const usePutOrganizationsByOrgIdSalonsBySalonIdKey = "PutOrganizationsByOrgIdSalonsBySalonId";
export const UsePutOrganizationsByOrgIdSalonsBySalonIdKeyFn = (mutationKey?: Array<unknown>) => [usePutOrganizationsByOrgIdSalonsBySalonIdKey, ...(mutationKey ?? [])];
export type PutOrganizationsByOrgIdServicesByIdMutationResult = Awaited<ReturnType<typeof putOrganizationsByOrgIdServicesById>>;
export const usePutOrganizationsByOrgIdServicesByIdKey = "PutOrganizationsByOrgIdServicesById";
export const UsePutOrganizationsByOrgIdServicesByIdKeyFn = (mutationKey?: Array<unknown>) => [usePutOrganizationsByOrgIdServicesByIdKey, ...(mutationKey ?? [])];
export type PutPublicBookingsByIdRescheduleMutationResult = Awaited<ReturnType<typeof putPublicBookingsByIdReschedule>>;
export const usePutPublicBookingsByIdRescheduleKey = "PutPublicBookingsByIdReschedule";
export const UsePutPublicBookingsByIdRescheduleKeyFn = (mutationKey?: Array<unknown>) => [usePutPublicBookingsByIdRescheduleKey, ...(mutationKey ?? [])];
export type PatchOrganizationsByOrgIdBookingsByIdDurationMutationResult = Awaited<ReturnType<typeof patchOrganizationsByOrgIdBookingsByIdDuration>>;
export const usePatchOrganizationsByOrgIdBookingsByIdDurationKey = "PatchOrganizationsByOrgIdBookingsByIdDuration";
export const UsePatchOrganizationsByOrgIdBookingsByIdDurationKeyFn = (mutationKey?: Array<unknown>) => [usePatchOrganizationsByOrgIdBookingsByIdDurationKey, ...(mutationKey ?? [])];
export type DeleteOrganizationsByOrgIdBookingsByIdRescheduleMutationResult = Awaited<ReturnType<typeof deleteOrganizationsByOrgIdBookingsByIdReschedule>>;
export const useDeleteOrganizationsByOrgIdBookingsByIdRescheduleKey = "DeleteOrganizationsByOrgIdBookingsByIdReschedule";
export const UseDeleteOrganizationsByOrgIdBookingsByIdRescheduleKeyFn = (mutationKey?: Array<unknown>) => [useDeleteOrganizationsByOrgIdBookingsByIdRescheduleKey, ...(mutationKey ?? [])];
export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdMutationResult = Awaited<ReturnType<typeof deleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonId>>;
export const useDeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdKey = "DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonId";
export const UseDeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdKey, ...(mutationKey ?? [])];
export type DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateMutationResult = Awaited<ReturnType<typeof deleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDate>>;
export const useDeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateKey = "DeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDate";
export const UseDeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateKeyFn = (mutationKey?: Array<unknown>) => [useDeleteOrganizationsByOrgIdMastersByMasterIdSalonsBySalonIdScheduleExceptionsByDateKey, ...(mutationKey ?? [])];
export type DeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdMutationResult = Awaited<ReturnType<typeof deleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceId>>;
export const useDeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdKey = "DeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceId";
export const UseDeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteOrganizationsByOrgIdMastersByMasterIdServicesByServiceIdKey, ...(mutationKey ?? [])];
export type DeleteOrganizationsByOrgIdMembersByVkIdMutationResult = Awaited<ReturnType<typeof deleteOrganizationsByOrgIdMembersByVkId>>;
export const useDeleteOrganizationsByOrgIdMembersByVkIdKey = "DeleteOrganizationsByOrgIdMembersByVkId";
export const UseDeleteOrganizationsByOrgIdMembersByVkIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteOrganizationsByOrgIdMembersByVkIdKey, ...(mutationKey ?? [])];
export type DeleteOrganizationsByOrgIdRolesByRoleIdMutationResult = Awaited<ReturnType<typeof deleteOrganizationsByOrgIdRolesByRoleId>>;
export const useDeleteOrganizationsByOrgIdRolesByRoleIdKey = "DeleteOrganizationsByOrgIdRolesByRoleId";
export const UseDeleteOrganizationsByOrgIdRolesByRoleIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteOrganizationsByOrgIdRolesByRoleIdKey, ...(mutationKey ?? [])];
export type DeleteOrganizationsByOrgIdSalonsBySalonIdMutationResult = Awaited<ReturnType<typeof deleteOrganizationsByOrgIdSalonsBySalonId>>;
export const useDeleteOrganizationsByOrgIdSalonsBySalonIdKey = "DeleteOrganizationsByOrgIdSalonsBySalonId";
export const UseDeleteOrganizationsByOrgIdSalonsBySalonIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteOrganizationsByOrgIdSalonsBySalonIdKey, ...(mutationKey ?? [])];
export type DeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdMutationResult = Awaited<ReturnType<typeof deleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceId>>;
export const useDeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdKey = "DeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceId";
export const UseDeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteOrganizationsByOrgIdSalonsBySalonIdExcludedServicesByServiceIdKey, ...(mutationKey ?? [])];
export type DeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneMutationResult = Awaited<ReturnType<typeof deleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhone>>;
export const useDeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneKey = "DeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhone";
export const UseDeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneKeyFn = (mutationKey?: Array<unknown>) => [useDeleteOrganizationsByOrgIdSalonsBySalonIdPhonesByPhoneKey, ...(mutationKey ?? [])];
export type DeletePublicBookingsByIdMutationResult = Awaited<ReturnType<typeof deletePublicBookingsById>>;
export const useDeletePublicBookingsByIdKey = "DeletePublicBookingsById";
export const UseDeletePublicBookingsByIdKeyFn = (mutationKey?: Array<unknown>) => [useDeletePublicBookingsByIdKey, ...(mutationKey ?? [])];
export type DeletePublicWaitlistByIdMutationResult = Awaited<ReturnType<typeof deletePublicWaitlistById>>;
export const useDeletePublicWaitlistByIdKey = "DeletePublicWaitlistById";
export const UseDeletePublicWaitlistByIdKeyFn = (mutationKey?: Array<unknown>) => [useDeletePublicWaitlistByIdKey, ...(mutationKey ?? [])];
