export const TimeSlotStatus = {
  TIME_SLOT_STATUS_UNSPECIFIED: "0",
  TIME_SLOT_STATUS_AVAILABLE: "1",
  TIME_SLOT_STATUS_RESERVED: "2",
  TIME_SLOT_STATUS_BOOKED: "3",
  TIME_SLOT_STATUS_CANCELLED: "4",
};
